### ISSUE TITLE
where is it games java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#106]
bug at least on windows with tobii 4C

`2017-12-16 10:55:49,206 [JavaFX Application Thread]    INFO  net.gazeplay.games.whereisit.WhereIsIt - posX 1
2017-12-16 10:55:49,206 [JavaFX Application Thread]    INFO  net.gazeplay.games.whereisit.WhereIsIt - posY 1
2017-12-16 10:55:49,234 [Thread-6]                     DEBUG net.gazeplay.games.whereisit.WhereIsIt$Pictures - ENTERED
2017-12-16 10:55:49,254 [Thread-6]                     DEBUG net.gazeplay.games.whereisit.WhereIsIt$Pictures - ENTERED
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.elementData(Unknown Source)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.get(Unknown Source)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1591)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1535)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateGeomBounds(Node.java:3579)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getGeomBounds(Node.java:3532)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getLocalBounds(Node.java:3480)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateTxBounds(Node.java:3643)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getTransformedBounds(Node.java:3426)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateBounds(Node.java:559)
2017-12-16 10:55:49,259 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1719)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1717)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.security.AccessController.doPrivileged(Native Method)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
2017-12-16 10:55:49,260 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.lang.Thread.run(Unknown Source)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.elementData(Unknown Source)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.get(Unknown Source)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1591)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1535)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateGeomBounds(Node.java:3579)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getGeomBounds(Node.java:3532)
2017-12-16 10:55:49,274 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getLocalBounds(Node.java:3480)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateTxBounds(Node.java:3643)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getTransformedBounds(Node.java:3426)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateBounds(Node.java:559)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1719)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1717)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.security.AccessController.doPrivileged(Native Method)
2017-12-16 10:55:49,275 [Thread-6]                     DEBUG net.gazeplay.games.whereisit.WhereIsIt$Pictures - ENTERED
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
2017-12-16 10:55:49,275 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.lang.Thread.run(Unknown Source)
2017-12-16 10:55:49,290 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2017-12-16 10:55:49,291 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.elementData(Unknown Source)
2017-12-16 10:55:49,291 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.get(Unknown Source)
2017-12-16 10:55:49,291 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
2017-12-16 10:55:49,291 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1591)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1535)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateGeomBounds(Node.java:3579)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getGeomBounds(Node.java:3532)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getLocalBounds(Node.java:3480)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateTxBounds(Node.java:3643)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getTransformedBounds(Node.java:3426)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateBounds(Node.java:559)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1719)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1717)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.security.AccessController.doPrivileged(Native Method)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
2017-12-16 10:55:49,292 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.lang.Thread.run(Unknown Source)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.elementData(Unknown Source)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.get(Unknown Source)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1591)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1535)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateGeomBounds(Node.java:3579)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getGeomBounds(Node.java:3532)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getLocalBounds(Node.java:3480)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateTxBounds(Node.java:3643)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getTransformedBounds(Node.java:3426)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateBounds(Node.java:559)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1719)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1717)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.security.AccessController.doPrivileged(Native Method)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
2017-12-16 10:55:49,306 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
2017-12-16 10:55:49,307 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
2017-12-16 10:55:49,307 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
2017-12-16 10:55:49,307 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2017-12-16 10:55:49,307 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2017-12-16 10:55:49,307 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
2017-12-16 10:55:49,307 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.lang.Thread.run(Unknown Source)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.elementData(Unknown Source)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.util.ArrayList.get(Unknown Source)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1591)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1535)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateGeomBounds(Node.java:3579)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getGeomBounds(Node.java:3532)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getLocalBounds(Node.java:3480)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateTxBounds(Node.java:3643)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.getTransformedBounds(Node.java:3426)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Node.updateBounds(Node.java:559)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1719)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Parent.updateBounds(Parent.java:1717)
2017-12-16 10:55:49,322 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.security.AccessController.doPrivileged(Native Method)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
2017-12-16 10:55:49,323 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.lang.Thread.run(Unknown Source)
2017-12-16 10:55:49,338 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,354 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,386 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,402 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,418 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,434 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,450 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,467 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,482 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,499 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,514 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,530 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,546 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,562 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,578 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,595 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,610 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,626 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,643 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,648 [Thread-6]                     DEBUG net.gazeplay.games.whereisit.WhereIsIt$Pictures - ENTERED
2017-12-16 10:55:49,658 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,674 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,691 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,700 [Thread-6]                     DEBUG net.gazeplay.games.whereisit.WhereIsIt$Pictures - ENTERED
2017-12-16 10:55:49,706 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,722 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,738 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,755 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,770 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,786 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,802 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,819 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,835 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,850 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,867 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,882 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,898 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,914 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,930 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,946 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,962 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2017-12-16 10:55:49,978 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException`

**Comment by schwabdidier** [comment]
I see `[Thread-6] DEBUG net.gazeplay.games.whereisit.WhereIsIt$Pictures - ENTERED `

What is this thread ?

**Comment by schwabdidier** [comment]
The problem was that event were on Picture objects instead of imageRectangle one of the members of Picture. Hence all members of Picture could handle the event including progress bar launching the bug. -> events have to be only on the actual object.
