### ISSUE TITLE
impossible to go to version 1.1.1

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#120]
@YannRobert : after the pull request #117 I am unable to upgrade to version 1.1.1 (even if everything seems to be in version 1.1.0).

find ~/.m2/repository -name "*gazeplay*" | xargs rm -rf

OK

mvn clean install

OK

mvn clean license:download-licenses license:add-third-party release:prepare 

```
...
[INFO] ------------------------------------------------------------------------
[INFO] Building gazeplay-project 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-release-plugin:2.5.3:prepare (default-cli) @ gazeplay-project ---
[INFO] Resuming release from phase 'run-preparation-goals'
[INFO] Executing goals 'verify'...
[INFO] Executing: /bin/sh -c cd /Users/schwab/Documents/GazePlay && "/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/mvn" -s /var/folders/pj/758ssnf55dx91w5l4s7_1s_c0000gn/T/release-settings3928098211798221601.xml verify --no-plugin-updates
    /bin/sh: /Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/mvn: Permission denied
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gazeplay-project ................................... FAILURE [  0.640 s]
[INFO] gazeplay-commons ................................... SUCCESS [  7.400 s]
[INFO] gazeplay-data ...................................... SUCCESS [  0.077 s]
[INFO] gazeplay ........................................... SUCCESS [  4.913 s]
[INFO] gazeplay-side-projects ............................. SUCCESS [  2.958 s]
[INFO] gazeplay-picto-pick ................................ SUCCESS [  2.943 s]
[INFO] gazeplay-melordi ................................... SUCCESS [  2.942 s]
[INFO] gazeplay-dist ...................................... SUCCESS [  3.413 s]
[INFO] gazeplay-dlls ...................................... SUCCESS [  0.013 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.328 s
[INFO] Finished at: 2017-12-26T16:50:10+01:00
[INFO] Final Memory: 25M/313M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project gazeplay-project: Maven execution failed, exit code: '126' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1
```

**Comment by YannRobert** [comment]
I guess you're using a Mac?

Is the file ```/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/mvn``` executable ?

if not, try 
```
chmod +x /Applications/IntelliJ\ IDEA.app/Contents/plugins/maven/lib/maven3/bin/mvn
```

Anyways, please check why you are using a mvn from your IntelliJ installation.
You would maybe better use an official Maven distribution, that you download, unzip and add to you PATH.

**Comment by schwabdidier** [comment]
it is a little bit different now.

```
[INFO] ------------------------------------------------------------------------
[INFO] Building gazeplay-project 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-release-plugin:2.5.3:prepare (default-cli) @ gazeplay-project ---
[INFO] Resuming release from phase 'run-preparation-goals'
[INFO] Executing goals 'verify'...
[INFO] Executing: /bin/sh -c cd /Users/schwab/Documents/GazePlay && "/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/mvn" -s /var/folders/pj/758ssnf55dx91w5l4s7_1s_c0000gn/T/release-settings1141179794825876443.xml verify --no-plugin-updates
    Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
    	at java.lang.ClassLoader.defineClass1(Native Method)
    	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
    	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
    	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gazeplay-project ................................... FAILURE [  1.214 s]
[INFO] gazeplay-commons ................................... SUCCESS [  6.915 s]
[INFO] gazeplay-data ...................................... SUCCESS [  0.074 s]
[INFO] gazeplay ........................................... SUCCESS [  6.310 s]
[INFO] gazeplay-side-projects ............................. SUCCESS [  4.228 s]
[INFO] gazeplay-picto-pick ................................ SUCCESS [  3.904 s]
[INFO] gazeplay-melordi ................................... SUCCESS [  3.726 s]
[INFO] gazeplay-dist ...................................... SUCCESS [  4.422 s]
[INFO] gazeplay-dlls ...................................... SUCCESS [  0.020 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.852 s
[INFO] Finished at: 2017-12-28T19:00:53+01:00
[INFO] Final Memory: 23M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project gazeplay-project: Maven execution failed, exit code: '1' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1
```

**Comment by schwabdidier** [comment]
I just tried with the official version (3.5.2). I have still an error... not the same one...

```
[INFO] ------------------------------------------------------------------------
[INFO] Building gazeplay-project 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-release-plugin:2.5.3:prepare (default-cli) @ gazeplay-project ---
[INFO] Resuming release from phase 'scm-commit-release'
[INFO] Checking in modified POMs...
[INFO] Executing: /bin/sh -c cd /Users/schwab/Documents/GazePlay && git add -- pom.xml gazeplay-commons/pom.xml gazeplay-data/pom.xml gazeplay/pom.xml gazeplay-side-projects/pom.xml gazeplay-picto-pick/pom.xml gazeplay-melordi/pom.xml gazeplay-dist/pom.xml gazeplay-dlls/pom.xml
[INFO] Working directory: /Users/schwab/Documents/GazePlay
[INFO] Executing: /bin/sh -c cd /Users/schwab/Documents/GazePlay && git rev-parse --show-toplevel
[INFO] Working directory: /Users/schwab/Documents/GazePlay
[INFO] Executing: /bin/sh -c cd /Users/schwab/Documents/GazePlay && git status --porcelain .
[INFO] Working directory: /Users/schwab/Documents/GazePlay
[WARNING] Ignoring unrecognized line: ?? .DS_Store
[WARNING] Ignoring unrecognized line: ?? Old-website/README.md
[WARNING] Ignoring unrecognized line: ?? gazeplay-commons/pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/multilinguism/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/ninja/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/ninja/sounds/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/.~lock.animals.csv#
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/bears/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/bees/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/cats/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/crocodiles/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/dogs/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/eagles/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/elephants/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/horses/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/lions/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/owls/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/parrots/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/pigeons/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/rabbits/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/squirrels/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/tigers/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-animal/images/turtles/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/black/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/blue/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/brown/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/green/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/grey/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/orange/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/pink/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/purple/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/red/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/white/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-data/src/main/resources/data/where-is-the-color/images/yellow/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-dist/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay-dist/pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? gazeplay-dlls/pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? gazeplay-melordi/pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? gazeplay-picto-pick/pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? gazeplay-side-projects/pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? gazeplay/.DS_Store
[WARNING] Ignoring unrecognized line: ?? gazeplay/pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? gazeplay/src/main/resources/
[WARNING] Ignoring unrecognized line: ?? pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? release.properties
[INFO] Executing: /bin/sh -c cd /Users/schwab/Documents/GazePlay && git commit --verbose -F /var/folders/pj/758ssnf55dx91w5l4s7_1s_c0000gn/T/maven-scm-958961136.commit pom.xml gazeplay-commons/pom.xml gazeplay-data/pom.xml gazeplay/pom.xml gazeplay-side-projects/pom.xml gazeplay-picto-pick/pom.xml gazeplay-melordi/pom.xml gazeplay-dist/pom.xml gazeplay-dlls/pom.xml
[INFO] Working directory: /Users/schwab/Documents/GazePlay
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gazeplay-project ................................... FAILURE [  0.814 s]
[INFO] gazeplay-commons ................................... SUCCESS [  6.546 s]
[INFO] gazeplay-data ...................................... SUCCESS [  0.075 s]
[INFO] gazeplay ........................................... SUCCESS [  6.078 s]
[INFO] gazeplay-side-projects ............................. SUCCESS [  4.376 s]
[INFO] gazeplay-picto-pick ................................ SUCCESS [  3.864 s]
[INFO] gazeplay-melordi ................................... SUCCESS [  3.695 s]
[INFO] gazeplay-dist ...................................... SUCCESS [  4.479 s]
[INFO] gazeplay-dlls ...................................... SUCCESS [  0.015 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.783 s
[INFO] Finished at: 2017-12-28T19:17:51+01:00
[INFO] Final Memory: 25M/313M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project gazeplay-project: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-commit command failed.
[ERROR] Command output:
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1
```

**Comment by YannRobert** [comment]
Please check that the default Java you get on the command line is a Java 8 SDK
```
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
(exact minor version is not important)

Also check you have ```git``` on the PATH
```
$ git --version
git version 2.15.1
```
(exact version is not important)

If error persists, you generally get more detailed error message when adding ```-X``` option to the ```mvn``` command line

Please also check that your git working copy is clean before running a maven release.
```
$ git status
Sur la branche master
rien à valider, la copie de travail est propre
```

As you're working on Mac, you probably should add ```.DS_Store``` to the project ```.gitignore```.

**Comment by schwabdidier** [comment]
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java -Dvisualvm.id=1423443285985889 -Dmaven.multiModuleProjectDirectory=/Users/schwab/Documents/GazePlay -Dmaven.home=/Applications/apache-maven-3.5.2 -Dclassworlds.conf=/Applications/apache-maven-3.5.2/bin/m2.conf "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=63651:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Applications/apache-maven-3.5.2/boot/plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version=2017.3 java -version
objc[89492]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /Applications/apache-maven-3.5.2
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

**Comment by YannRobert** [comment]
Ouch, I don't understand what is the first line.

I don't remember how JVMs are installed on Mac. So I won't be of much help.
I guess you can find a solution on the web.

**Comment by schwabdidier** [comment]
It was in intellij. I tried on my terminal.

I have that, maybe it is the problem

```
git --version
git version 2.8.4 (Apple Git-73)
```

**Comment by schwabdidier** [comment]
It is ok !! I simply made a new project and reimported everything then upgrade to 1.1.1
