### ISSUE TITLE
bug with 4c connected or not

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#185]
```
2018-01-30 17:49:34,470 ERROR - Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: C:\Users\schwab\AppData\Local\Temp\lib\tobii\x64\vccorlib140.dll: Can't find dependent libraries
2018-01-30 17:49:34,470 ERROR - 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
2018-01-30 17:49:34,470 ERROR - 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
2018-01-30 17:49:34,470 ERROR - 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
2018-01-30 17:49:34,470 ERROR - 	at java.lang.Runtime.load0(Runtime.java:809)
2018-01-30 17:49:34,470 ERROR - 	at java.lang.System.load(System.java:1086)
2018-01-30 17:49:34,470 ERROR - 	at tobii.Tobii.loadLibrary(Tobii.java:74)
2018-01-30 17:49:34,470 ERROR - 	at tobii.Tobii.loadNeededLibraries(Tobii.java:46)
2018-01-30 17:49:34,470 ERROR - 	at tobii.Tobii.<init>(Tobii.java:25)
2018-01-30 17:49:34,470 ERROR - 	at tobii.Tobii.gazePosition(Tobii.java:16)
2018-01-30 17:49:34,470 ERROR - 	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager.init(TobiiGazeDeviceManager.java:22)
2018-01-30 17:49:34,470 ERROR - 	at net.gazeplay.commons.gaze.devicemanager.GazeDeviceManagerFactory.createNewGazeListener(GazeDeviceManagerFactory.java:53)
2018-01-30 17:49:34,471 ERROR - 	at net.gazeplay.GameContext.newInstance(GameContext.java:83)
2018-01-30 17:49:34,471 ERROR - 	at net.gazeplay.HomeMenuScreen.chooseGame(HomeMenuScreen.java:195)
2018-01-30 17:49:34,471 ERROR - 	at net.gazeplay.HomeMenuScreen.chooseGame(HomeMenuScreen.java:187)
2018-01-30 17:49:34,471 ERROR - 	at net.gazeplay.HomeMenuScreen.access$000(HomeMenuScreen.java:42)
2018-01-30 17:49:34,471 ERROR - 	at net.gazeplay.HomeMenuScreen$1.changed(HomeMenuScreen.java:157)
2018-01-30 17:49:34,471 ERROR - 	at net.gazeplay.HomeMenuScreen$1.changed(HomeMenuScreen.java:154)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
2018-01-30 17:49:34,471 ERROR - 	at javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:72)
2018-01-30 17:49:34,471 ERROR - 	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
2018-01-30 17:49:34,471 ERROR - 	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
2018-01-30 17:49:34,471 ERROR - 	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
2018-01-30 17:49:34,471 ERROR - 	at javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:68)
2018-01-30 17:49:34,471 ERROR - 	at javafx.scene.control.SingleSelectionModel.updateSelectedIndex(SingleSelectionModel.java:215)
2018-01-30 17:49:34,471 ERROR - 	at javafx.scene.control.SingleSelectionModel.select(SingleSelectionModel.java:149)
2018-01-30 17:49:34,471 ERROR - 	at javafx.scene.control.ChoiceBox$ChoiceBoxSelectionModel.select(ChoiceBox.java:573)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.scene.control.skin.ChoiceBoxSkin.lambda$addPopupItem$284(ChoiceBoxSkin.java:261)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
2018-01-30 17:49:34,471 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2018-01-30 17:49:34,471 ERROR - 	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2018-01-30 17:49:34,471 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2018-01-30 17:49:34,472 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2018-01-30 17:49:34,472 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
2018-01-30 17:49:34,472 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2018-01-30 17:49:34,472 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2018-01-30 17:49:34,472 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2018-01-30 17:49:34,472 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2018-01-30 17:49:34,472 ERROR - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
2018-01-30 17:49:34,472 ERROR - 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by coylz** [comment]
Hum ok... So it seems that it's impossible or at least really difficult to *properly* add the dependent dlls (the dlls from Visual C++ 2015 Redistributable) to the Java project, because some dlls are interdependent: for instance, msvc140.dll needs vccorlib140.dll and vice-versa. So when we try to load one dll, it crashes because we cannot load the two dlls at the same time.

The best solution I see is to install the MSVC Redistributable from Microsoft (URL : https://www.microsoft.com/download/details.aspx?id=48145) as part of the dependencies for running GazePlay. Either by telling people to do so (in the home page, just after "java is needed"), or to include it in the installer of GazePlay.

**Comment by YannRobert** [comment]
@coylz yes, you can "load multiple dlls at the same time", you need to 

* put every dll files in the same folder
* set this folder in the ```java.library.path``` system property of the JVM

With Java on Windows, the ```java.library.path``` system property will automatically be initialized with the PATH environment variable.

So the simplest thing to do is to add the dll folder to the PATH environment variable, 
either globally for the windows user (very easy to do at the beginning to start testing)
or just for the program you are running (when the directory location is not known in advance)

When you load a dll by name (not by file) then it will search in every folder that are listed in the ```java.library.path``` system property.
If a dll needs another dll, it will automatically search for it also in the ```java.library.path```. Your Java program does not need to load every dll. It just needs to load the highest level dll.

So in the end, when you execute the dll from a ```.bat``` file, you just need to set the ```PATH``` before starting the JVM.

When you execute the java program from the IDE, configure the IDE to add your dll directory to the ```java.library.path```

**Comment by coylz** [comment]
@YannRobert Ok you convinced me :) I'll make the changes this afternoon in the TobiiStreamEngineForJava project: I guess I'll copy the dlls from the resources to the user's AppData folder (on first call of Tobii.gazePosition, only if the dlls don't already exist), into something like %AppData%\TobiiStreamEngineForJava\lib\x64. Then we'll just need to add this path to the PATH variable and it should be alright ^^

**Comment by coylz** [comment]
See #161

**Comment by schwabdidier** [comment]
confirmed by users : It works  !!!

**Comment by coylz** [comment]
Nice ! What a relief :)
