### ISSUE TITLE
Where is it ? games

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#199]
First finding is ok, then tobii fails 

2018-02-02 14:21:04,279 [Thread-308]                   ERROR net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager - Exception on Gaze position update
java.lang.NullPointerException: null

**Comment by YannRobert** [comment]
Hi Didier, could you please share the first few lines of the stack trace ?

**Comment by schwabdidier** [comment]
No, it writes lines so fast, I was unable to see it in log (same thing in file) and I didn't find time to increase size.

**Comment by YannRobert** [comment]
reproduced 

```
 [Thread-6]                     ERROR net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager - Exception on Gaze position update
java.lang.NullPointerException: null
	at javafx.scene.Node.contains(Node.java:3916)
	at net.gazeplay.commons.gaze.devicemanager.AbstractGazeDeviceManager.onGazeUpdate(AbstractGazeDeviceManager.java:123)
	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager$1$1.call(TobiiGazeDeviceManager.java:47)
	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager$1$1.call(TobiiGazeDeviceManager.java:32)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.concurrent.Service.lambda$null$493(Service.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$494(Service.java:724)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by WaffleBuffer** [comment]
This issue should be closed i guess
