### ISSUE TITLE
MediaException: UNKNOWN on a linux

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#23]
Exception in thread "JavaFX Application Thread" MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
        at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
        at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:511)
        at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:414)
        at utils.games.Utils.playSound(Utils.java:279)

**Comment by schwabdidier** [comment]
May be fixed with 

https://stackoverflow.com/questions/35867990/debian-jessie-javafx-mediaplayer-could-not-create-player
