### ISSUE TITLE
Memory, pb with size 3*3

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#233]
on my mac, size 3*3 doesn't work. I get the multicolor wheel. I guess it is a memory problem ;)

**Comment by YannRobert** [comment]
I can reproduce
I took a thread dump

```
"JavaFX Application Thread" #17 prio=5 os_prio=0 tid=0x00007f94e0126800 nid=0x66bf runnable [0x00007f94d85de000]
   java.lang.Thread.State: RUNNABLE
	at net.gazeplay.games.memory.Memory.getRandomValue(Memory.java:189)
	at net.gazeplay.games.memory.Memory.createCards(Memory.java:157)
	at net.gazeplay.games.memory.Memory.launch(Memory.java:91)
	at net.gazeplay.HomeMenuScreen.chooseGame(HomeMenuScreen.java:302)
	at net.gazeplay.HomeMenuScreen.access$000(HomeMenuScreen.java:42)
	at net.gazeplay.HomeMenuScreen$1.handle(HomeMenuScreen.java:171)
	at net.gazeplay.HomeMenuScreen$1.handle(HomeMenuScreen.java:167)
```

This is an infinite loop issue.

**Comment by schwabdidier** [comment]
Odd, an infinite loop when there are 9 cards while no when there are on 6 🤔

**Comment by YannRobert** [comment]
May I look into it ?

**Comment by YannRobert** [comment]
I guess the total number of cards must be an even number.
But 9 is an odd number.

**Comment by schwabdidier** [comment]
Feel free to have a look

**Comment by schwabdidier** [comment]
I feel stupid :)
