### ISSUE TITLE
Pb of background music on MacOS 

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#259]
```
2018-02-25 22:17:56,375 INFO  - Finished setup stage with the game scene
2018-02-25 22:17:56,385 INFO  - Downloading music file https://opengameart.org/sites/default/files/010614songidea%28copycat%29_0.mp3
2018-02-25 22:17:56,805 ERROR - Exception in thread "Thread-232" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2018-02-25 22:17:56,805 ERROR - 	at net.gazeplay.commons.utils.games.BackgroundMusicManager.downloadAndGetFromCache(BackgroundMusicManager.java:149)
2018-02-25 22:17:56,805 ERROR - 	at net.gazeplay.commons.utils.games.BackgroundMusicManager.access$000(BackgroundMusicManager.java:22)
2018-02-25 22:17:56,805 ERROR - 	at net.gazeplay.commons.utils.games.BackgroundMusicManager$1.run(BackgroundMusicManager.java:92)
2018-02-25 22:17:56,805 ERROR - 	at java.lang.Thread.run(Thread.java:745)
2018-02-25 22:17:56,805 ERROR - Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2018-02-25 22:17:56,805 ERROR - 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
2018-02-25 22:17:56,805 ERROR - 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
2018-02-25 22:17:56,805 ERROR - 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
2018-02-25 22:17:56,806 ERROR - 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
2018-02-25 22:17:56,806 ERROR - 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
2018-02-25 22:17:56,806 ERROR - 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
2018-02-25 22:17:56,806 ERROR - 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
2018-02-25 22:17:56,806 ERROR - 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
2018-02-25 22:17:56,806 ERROR - 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
2018-02-25 22:17:56,806 ERROR - 	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1506)
2018-02-25 22:17:56,806 ERROR - 	at net.gazeplay.commons.utils.games.BackgroundMusicManager.downloadAndGetFromCache(BackgroundMusicManager.java:147)
```

**Comment by YannRobert** [comment]
Looks like the TLS Certificate Issuer (Let's Encrypt) is not accepted by your java trust store.

**Comment by schwabdidier** [comment]
It works now
