### ISSUE TITLE
Bug when loading stats in colors

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#348]
Exception when clicking on the home button in coloring : 
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
2018-05-07 10:08:22,048 ERROR - 	at java.io.File.<init>(File.java:360)
2018-05-07 10:08:22,048 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.getGameStatsOfTheDayDirectory(Stats.java:178)
2018-05-07 10:08:22,048 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveStats(Stats.java:109)
2018-05-07 10:08:22,048 ERROR - 	at net.gazeplay.GameContext.lambda$homeButtonClicked$3(GameContext.java:177)
2018-05-07 10:08:22,048 ERROR - 	at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:186)
2018-05-07 10:08:22,048 ERROR - 	at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$2(GameContext.java:157)
2018-05-07 10:08:22,048 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2018-05-07 10:08:22,049 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2018-05-07 10:08:22,049 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2018-05-07 10:08:22,049 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2018-05-07 10:08:22,049 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2018-05-07 10:08:22,049 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2018-05-07 10:08:22,049 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2018-05-07 10:08:22,049 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
2018-05-07 10:08:22,049 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2018-05-07 10:08:22,050 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2018-05-07 10:08:22,050 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
2018-05-07 10:08:22,050 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2018-05-07 10:08:22,050 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
2018-05-07 10:08:22,050 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2018-05-07 10:08:22,050 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2018-05-07 10:08:22,050 ERROR - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2018-05-07 10:08:22,050 ERROR - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
2018-05-07 10:08:22,050 ERROR - 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by WaffleBuffer** [comment]
I think i fixed it.

**Comment by WaffleBuffer** [comment]
I think this issue can be closed. It was actually caused by a change in Stats object creation and i didn't update the Color stats
