### ISSUE TITLE
Images not found when running from Netbeans IDE in game "Portrait"

### ISSUE THREAD

**Issue by Skullhack** [schwabdidier/GazePlay#359]
When I run games that use Portrait object as target like Ninja or Divisor, nothing shows up. I noticed that a new object ImageLibrary is used by Portrait, but I don't get why it doesn't work anymore.

Am I the only one that got only a black screen on those games ?

**Comment by YannRobert** [comment]
Any error or warning in logs ?

**Comment by Skullhack** [comment]
It looks like it's searching images in the wrong directory. I had to switch to Windows on my working laptop, maybe it's a path name error, but I think I had the error while I was on Linux too.

Can you recreate the error on a Linux setup please ? Simply launch Ninja for example, we'll see if it's coming from the OS.

**Comment by schwabdidier** [comment]
maybe you have a bad path in your options ?
On macOS, no problem.

**Comment by Skullhack** [comment]
I took a screenshot from the log. After adding images in the file directory (the one  referenced in options), the game are working because it use those images. But I don't get why the base images are not found.

![capture](https://user-images.githubusercontent.com/19265897/39926518-bd2e23be-552f-11e8-8638-991cdaa02877.PNG)

**Comment by YannRobert** [comment]
Are you launching from an IDE ? It is Intellij or anything else ?

**Comment by YannRobert** [comment]
Please send logs as text in markdown code blocks

**Comment by Skullhack** [comment]
Yes i'm launching from Netbeans.
Edited my previous answer with markdown.

**Comment by Skullhack** [comment]
[gazeplay.log](https://github.com/schwabdidier/GazePlay/files/1995646/gazeplay.log)

**Comment by YannRobert** [comment]
On IntelliJ, I have something like this

```
INFO  - filesFolder : /home/username/GazePlay/files/
INFO  - workingDirectory = /home/username/work/GazePlay/.
INFO  - workingDirectoryName = GazePlay
INFO  - parentImagesPackageResourceLocation = data/common/default/images/
INFO  - imagesDirectory = /home/username/work/GazePlay/./data/common/default/images
WARN  - Directory does not exist : /home/username/work/GazePlay/./data/common/default/images
INFO  - parentImagesPackageResourceLocation = data/common/default/images/
INFO  - parentImagesPackageResourceUrl = file:/home/username/work/GazePlay/gazeplay-data/target/classes/data/common/default/images/
INFO  - imagesDirectory = /home/username/work/GazePlay/gazeplay-data/target/classes/data/common/default/images
INFO  - Listing images in directory /home/username/work/GazePlay/gazeplay-data/target/classes/data/common/default/images
INFO  - Found 10 files in directory /home/username/work/GazePlay/gazeplay-data/target/classes/data/common/default/images
INFO  - Listing images in directory /home/username/GazePlay/files/images/portraits
INFO  - Found 13 files in directory /home/username/GazePlay/files/images/portraits
```

So it seems that : 
Module dependencies are made to the actual classpath of the module in my case.
Module dependencies are made to the JAR file in the maven local repository in your case.

"Module dependencies to the actual classpath of the module" is expected, in order to be able to locate the image folder and use java.io.File to load them (instead of using ClassLoader's resource loading).

Resource Loading from ClassLoader has been dropped, in order to avoid complex code that would use both methods to load images.
I think we should not restore it.

We should be able to find an alternative way of locating the data directory that would work in any case.

**Comment by Skullhack** [comment]
I asked another Windows user to try the game using Portrait, and he also got blackscreen, meaning the location of the image folder didn't work in his case too.

**Comment by schwabdidier** [comment]
@Skullhack You mean current released version ?

**Comment by Skullhack** [comment]
No on the lastest dev version from git, it was another student working on the project too.

**Comment by WaffleBuffer** [comment]
I don't experience the issue on my Windows using NetBeans

**Comment by kuhlkrein** [comment]
Using eclipse on every "portraits" games: 

2018-05-18 15:03:32,887 INFO  - Listing images in directory C:\Users\super\GazePlay\files\images\portraits
2018-05-18 15:03:32,887 INFO  - Found 0 files in directory C:\Users\super\GazePlay\files\images\portraits
2018-05-18 15:03:32,887 INFO  - result = Dimension2D [width = 1920.0, height = 1080.0]
2018-05-18 15:03:32,902 ERROR - Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: There are not enough distinct Images in the LazyImageLibrary : requested : 1, available : 0+0
2018-05-18 15:03:32,902 ERROR - 	at net.gazeplay.commons.utils.games.AbstractImageLibrary.pickMultipleRandomDistinctImages(AbstractImageLibrary.java:40)
2018-05-18 15:03:32,903 ERROR - 	at net.gazeplay.commons.utils.games.AbstractImageLibrary.pickRandomImage(AbstractImageLibrary.java:28)
2018-05-18 15:03:32,903 ERROR - 	at net.gazeplay.commons.utils.Portrait.<init>(Portrait.java:32)
2018-05-18 15:03:32,903 ERROR - 	at net.gazeplay.games.ninja.Target.<init>(Target.java:54)
2018-05-18 15:03:32,903 ERROR - 	at net.gazeplay.games.ninja.Ninja.launch(Ninja.java:25)
2018-05-18 15:03:32,903 ERROR - 	at net.gazeplay.GameMenuFactory.chooseGame(GameMenuFactory.java:313)
2018-05-18 15:03:32,903 ERROR - 	at net.gazeplay.GameMenuFactory.access$3(GameMenuFactory.java:283)
2018-05-18 15:03:32,903 ERROR - 	at net.gazeplay.GameMenuFactory$1.handle(GameMenuFactory.java:221)
2018-05-18 15:03:32,904 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2018-05-18 15:03:32,904 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2018-05-18 15:03:32,904 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2018-05-18 15:03:32,904 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2018-05-18 15:03:32,905 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2018-05-18 15:03:32,905 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2018-05-18 15:03:32,905 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-18 15:03:32,905 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-18 15:03:32,906 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-18 15:03:32,906 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-18 15:03:32,907 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-18 15:03:32,907 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-18 15:03:32,907 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-18 15:03:32,908 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-18 15:03:32,908 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-18 15:03:32,908 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2018-05-18 15:03:32,908 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2018-05-18 15:03:32,908 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2018-05-18 15:03:32,909 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2018-05-18 15:03:32,909 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2018-05-18 15:03:32,909 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2018-05-18 15:03:32,909 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2018-05-18 15:03:32,909 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2018-05-18 15:03:32,910 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2018-05-18 15:03:32,910 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
2018-05-18 15:03:32,910 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2018-05-18 15:03:32,910 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2018-05-18 15:03:32,910 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
2018-05-18 15:03:32,911 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2018-05-18 15:03:32,911 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
2018-05-18 15:03:32,911 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2018-05-18 15:03:32,911 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2018-05-18 15:03:32,911 ERROR - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2018-05-18 15:03:32,911 ERROR - 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
2018-05-18 15:03:32,911 ERROR - 	at java.lang.Thread.run(Thread.java:745)


I check the gazeplay repo: No files directory ... I think it's due to that thing.

![image](https://user-images.githubusercontent.com/24478346/40236225-1d2ad276-5aad-11e8-9798-6c32832fa4f0.png)

**Comment by kuhlkrein** [comment]
@YannRobert 
for me line 31 of ImageUtils.java:
changing
`
 if (defaultImageDirectory == null) {
            defaultImageDirectory = ImageDirectoryLocator
                    .locateImagesDirectoryInExplodedClassPath("data/common/default/images/");
        }
`

by 

` if (defaultImageDirectory == null) {
            defaultImageDirectory = ImageDirectoryLocator
                    .locateImagesDirectoryInExplodedClassPath("gazeplay-data/src/main/resources/data/common/default/images/");
        }`

works. so the problem should be in the ImageDirectoryLocator.locateImagesDirectoryInExplodedClassPath funciton

**Comment by WaffleBuffer** [comment]
Could this solve issue #390? Have you tried using "mvn install" to solve the issue without having to change path ?

**Comment by kuhlkrein** [comment]
@WaffleBuffer I think it's the same kind of problem yes but we don't have to use this modification I think. It just means that the error is in the DirectoryLocators classes, probably in the function that return the complete path.
We need to find which function is looking for the complete path and we have to modify it.
(yes of course I'm used to mvn clean install my project every morning and before a pull request)

**Comment by WaffleBuffer** [comment]
ok, because i had some issues with images once and mvn clean install solved it but here i think you're right about what's causing the issue.

**Comment by WaffleBuffer** [comment]
Are you still experiencing this issue ?

**Comment by kuhlkrein** [comment]
@WaffleBuffer, For me it's ok now

**Comment by Skullhack** [comment]
Seems good for me too.

**Comment by WaffleBuffer** [comment]
Can we close this issue then ?
