### ISSUE TITLE
Bubbles Exception

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#401]
Bubbles game generate exceptions (in my local version) about creation of media player.

**Comment by schwabdidier** [comment]
Please, copy paste them...

**Comment by WaffleBuffer** [comment]
javafx.scene.media.MediaException: com.sun.media.jfxmedia.MediaException: Could not create player!
	at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:511)
	at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:414)
	at net.gazeplay.commons.utils.games.Utils.playSound(Utils.java:76)
	at net.gazeplay.games.bubbles.Bubble.explose(Bubble.java:182)
	at net.gazeplay.games.bubbles.Bubble.enter(Bubble.java:201)
	at net.gazeplay.games.bubbles.Bubble.access$000(Bubble.java:33)
	at net.gazeplay.games.bubbles.Bubble$1.handle(Bubble.java:86)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:282)
	at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:223)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at com.sun.javafx.event.EventQueue.fire(EventQueue.java:48)
	at javafx.scene.Scene$MouseHandler.handleEnterExit(Scene.java:3676)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3742)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:274)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:467)
	... 37 common frames omitted

**Comment by schwabdidier** [comment]
is it still an issue ?

**Comment by kuhlkrein** [comment]
No, @YannRobert fixed it on 30 oct 19 with #908 , he added "synchronized" to avoid this kind of problem. I'm closing.
