### ISSUE TITLE
Problem with tobii on heatmap funcitons

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#418]
```
java.lang.NullPointerException: null
	at net.gazeplay.commons.utils.stats.Stats.inc(Stats.java:241)
	at net.gazeplay.commons.utils.stats.Stats.incHeatMap(Stats.java:235)
	at net.gazeplay.commons.utils.stats.Stats.gazeMoved(Stats.java:104)
	at net.gazeplay.commons.gaze.devicemanager.AbstractGazeDeviceManager.notifyAllGazeMotionListeners(AbstractGazeDeviceManager.java:51)
	at net.gazeplay.commons.gaze.devicemanager.AbstractGazeDeviceManager.onGazeUpdate(AbstractGazeDeviceManager.java:101)
	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager$1$1.call(TobiiGazeDeviceManager.java:47)
	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager$1$1.call(TobiiGazeDeviceManager.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javafx.concurrent.Service.lambda$null$492(Service.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$493(Service.java:724)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```'

**Comment by WaffleBuffer** [comment]
Does this come from a particular game ?

**Comment by kuhlkrein** [comment]
It was when launching gazeplay I think

**Comment by WaffleBuffer** [comment]
Do you still experience this issue ? i've never seen it. Also did you deactivate the heat map ?
