### ISSUE TITLE
Bravo sound not found

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#457]
When the "Bravo" sound needs to be played i get this : 
2018-05-31 13:38:45,590 INFO  - path file:/home/medard/NetBeansProjects/GazePlay/gazeplay/file:/home/medard/NetBeansProjects/GazePlay/gazeplay-data/target/classes/data/common/sounds/applause.mp3
2018-05-31 13:38:49,596 ERROR - Exception
javafx.scene.media.MediaException: /home/medard/NetBeansProjects/GazePlay/gazeplay/file:/home/medard/NetBeansProjects/GazePlay/gazeplay-data/target/classes/data/common/sounds/applause.mp3 (No such file or directory)
	at javafx.scene.media.Media.<init>(Media.java:407)
	at net.gazeplay.commons.utils.games.Utils.playSound(Utils.java:76)
	at net.gazeplay.commons.utils.Bravo.lambda$delayedStart$1(Bravo.java:113)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

**Comment by WaffleBuffer** [comment]
This is weird because the file is where the path in the exception said

**Comment by WaffleBuffer** [comment]
Fixed in PR #465
