### ISSUE TITLE
bug at the end of order

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#518]
`2018-07-03 15:12:55,501 ERROR - Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: Java heap space
2018-07-03 15:12:55,502 ERROR -         at java.awt.image.DataBufferByte.<init>(Unknown Source)
2018-07-03 15:12:55,502 ERROR -         at java.awt.image.Raster.createInterleavedRaster(Unknown Source)
2018-07-03 15:12:55,502 ERROR -         at java.awt.image.BufferedImage.<init>(Unknown Source)
2018-07-03 15:12:55,502 ERROR -         at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1250)
2018-07-03 15:12:55,502 ERROR -         at org.tc33.jheatchart.HeatChart.saveToFile(HeatChart.java:1205)
2018-07-03 15:12:55,502 ERROR -         at net.gazeplay.commons.utils.stats.Stats.saveHeatMapAsPng(Stats.java:218)
2018-07-03 15:12:55,502 ERROR -         at net.gazeplay.commons.utils.stats.Stats.saveStats(Stats.java:117)
2018-07-03 15:12:55,502 ERROR -         at net.gazeplay.commons.utils.stats.ShootGamesStats.saveStats(ShootGamesStats.java:17)
2018-07-03 15:12:55,502 ERROR -         at net.gazeplay.GameContext.lambda$homeButtonClicked$19(GameContext.java:339)
2018-07-03 15:12:55,502 ERROR -         at net.gazeplay.GameContext$$Lambda$349/926907027.run(Unknown Source)
2018-07-03 15:12:55,502 ERROR -         at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:348)
2018-07-03 15:12:55,502 ERROR -         at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$18(GameContext.java:319)
2018-07-03 15:12:55,502 ERROR -         at net.gazeplay.GameContext$$Lambda$323/52469737.handle(Unknown Source)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2018-07-03 15:12:55,502 ERROR -         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2018-07-03 15:12:55,502 ERROR -         at javafx.event.Event.fireEvent(Event.java:198)
2018-07-03 15:12:55,502 ERROR -         at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2018-07-03 15:12:55,502 ERROR -         at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2018-07-03 15:12:55,502 ERROR -         at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2018-07-03 15:12:55,502 ERROR -         at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2018-07-03 15:12:55,502 ERROR -         at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2018-07-03 15:13:01,037 INFO  - Nodes not removed: 0
2018-07-03 15:13:01,037 ERROR - Exception in thread "JavaFX Application Thread" net.gazeplay.commons.utils.stats.LifeCycle$LifeCycleControlException: already stopped
2018-07-03 15:13:01,038 ERROR -         at net.gazeplay.commons.utils.stats.LifeCycle.stop(LifeCycle.java:52)
2018-07-03 15:13:01,038 ERROR -         at net.gazeplay.commons.utils.stats.Stats.stop(Stats.java:89)
2018-07-03 15:13:01,038 ERROR -         at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:333)
2018-07-03 15:13:01,038 ERROR -         at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$18(GameContext.java:319)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2018-07-03 15:13:01,038 ERROR -         at javafx.event.Event.fireEvent(Event.java:198)
2018-07-03 15:13:01,038 ERROR -         at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2018-07-03 15:13:01,038 ERROR -         at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2018-07-03 15:13:01,038 ERROR -         at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2018-07-03 15:13:01,038 ERROR -         at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2018-07-03 15:13:01,038 ERROR -         at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2018-07-03 15:13:01,038 ERROR -         at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2018-07-03 15:13:01,038 ERROR -         at java.security.AccessController.doPrivileged(Native Method)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2018-07-03 15:13:01,038 ERROR -         at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
2018-07-03 15:13:01,038 ERROR -         at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2018-07-03 15:13:01,038 ERROR -         at com.sun.glass.ui.View.notifyMouse(View.java:937)
2018-07-03 15:13:01,038 ERROR -         at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2018-07-03 15:13:01,038 ERROR -         at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
2018-07-03 15:13:01,038 ERROR -         at java.lang.Thread.run(Unknown Source)
`

**Comment by schwabdidier** [comment]
too old
