### ISSUE TITLE
Exception at the end of all games ?

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#566]
often (not always), when clicking home button, the following exception is launch (GazePlay 1.4.0 on windows with Tobii 4C)

```
2018-07-22 19:09:29,750 [JavaFX Application Thread]    DEBUG net.gazeplay.commons.utils.Bravo - finished onFinishedEventHandler
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - java.lang.InterruptedException: sleep interrupted
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at java.lang.Thread.sleep(Native Method)
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager$1$1.call(TobiiGazeDeviceManager.java:69)
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager$1$1.call(TobiiGazeDeviceManager.java:39)
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at java.util.concurrent.FutureTask.run(Unknown Source)
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at javafx.concurrent.Service.lambda$null$493(Service.java:725)
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at java.security.AccessController.doPrivileged(Native Method)
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at javafx.concurrent.Service.lambda$executeTask$494(Service.java:724)
2018-07-22 19:09:30,622 [JavaFX Application Thread]    INFO  net.gazeplay.commons.utils.stats.Stats - outputDirectoryCreated = true
2018-07-22 19:09:30,622 [Thread-11]                    ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2018-07-22 19:09:30,623 [Thread-11]                    ERROR java.lang.Throwable - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2018-07-22 19:09:30,623 [Thread-11]                    ERROR java.lang.Throwable - 	at java.lang.Thread.run(Unknown Source)
2018-07-22 19:09:30,623 [JavaFX Application Thread]    INFO  net.gazeplay.commons.utils.stats.Stats - Heatmap size: 200 X 125
2018-07-22 19:09:31,051 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: Java heap space
2018-07-22 19:09:31,051 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.awt.image.DataBufferByte.<init>(Unknown Source)
2018-07-22 19:09:31,051 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.awt.image.Raster.createInterleavedRaster(Unknown Source)
2018-07-22 19:09:31,051 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.awt.image.BufferedImage.<init>(Unknown Source)
2018-07-22 19:09:31,051 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1253)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at org.tc33.jheatchart.HeatChart.saveToFile(HeatChart.java:1208)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.commons.utils.stats.Stats.saveHeatMapAsPng(Stats.java:218)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.commons.utils.stats.Stats.saveStats(Stats.java:117)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.commons.utils.stats.HiddenItemsGamesStats.saveStats(HiddenItemsGamesStats.java:18)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GameContext.lambda$homeButtonClicked$19(GameContext.java:339)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GameContext$$Lambda$368/1030915992.run(Unknown Source)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:348)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$18(GameContext.java:319)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GameContext$$Lambda$360/1233821629.handle(Unknown Source)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.event.Event.fireEvent(Event.java:198)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2018-07-22 19:09:31,052 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2018-07-22 19:09:31,053 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2018-07-22 19:09:31,053 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
```

**Comment by schwabdidier** [comment]
I resolved with

`java -Xms256m -Xmx2g -jar ..\lib\gazeplay-1.4.0-SNAPSHOT.jar
`

instead of

`java -Xms256m -Xmx1g -jar ..\lib\gazeplay-1.4.0-SNAPSHOT.jar
`

**Comment by kuhlkrein** [comment]
Ah ok, yes effectively I added the same options on eclipse.

**Comment by kuhlkrein** [comment]
Maybe we could try to reduce the size of the heatmap ? I noticed that generally this error is due to the generation of this map...

**Comment by schwabdidier** [comment]
we also have an option to avoid to compute it. I changed it is in last commit
