### ISSUE TITLE
bug with sounds with French (at least)

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#648]
@johzz-o2  In order to resolve this bug, please do as me for "where is this animal?" or propose another solution. Maybe catching the exception if there is no file would be better.

`javafx.scene.media.MediaException: /Users/schwab/Documents/GazePlay/data/find-flag/sounds/fra/Greece.m.fra.mp3 (No such file or directory)
	at javafx.scene.media.Media.<init>(Media.java:405)
	at net.gazeplay.commons.utils.games.Utils.playSound(Utils.java:82)
	at net.gazeplay.games.whereisit.WhereIsIt.playQuestionSound(WhereIsIt.java:215)
	at net.gazeplay.games.whereisit.WhereIsIt.access$1900(WhereIsIt.java:47)
	at net.gazeplay.games.whereisit.WhereIsIt$PictureCard$3.handle(WhereIsIt.java:727)
	at net.gazeplay.games.whereisit.WhereIsIt$PictureCard$3.handle(WhereIsIt.java:724)
	at javafx.animation.Animation.impl_finished(Animation.java:1132)
	at javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$26(Animation.java:186)
	at javafx.animation.Animation$1$$Lambda$251/585791780.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:521)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$44/1238209112.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)`

**Comment by schwabdidier** [comment]
done
