### ISSUE TITLE
Exception in rush hour 

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#683]
occured only once :
2019-04-02 10:04:06,694 ERROR - Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
2019-04-02 10:04:06,694 ERROR - 	at net.gazeplay.games.rushHour.RushHour.lambda$2(RushHour.java:86)
2019-04-02 10:04:06,694 ERROR - 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
2019-04-02 10:04:06,695 ERROR - 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
2019-04-02 10:04:06,695 ERROR - 	at javafx.beans.property.IntegerPropertyBase.fireValueChangedEvent(IntegerPropertyBase.java:106)
2019-04-02 10:04:06,695 ERROR - 	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
2019-04-02 10:04:06,695 ERROR - 	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
2019-04-02 10:04:06,695 ERROR - 	at net.gazeplay.games.rushHour.RushHour.setLevel0(RushHour.java:186)
2019-04-02 10:04:06,695 ERROR - 	at net.gazeplay.games.rushHour.RushHour.setLevel(RushHour.java:98)
2019-04-02 10:04:06,695 ERROR - 	at net.gazeplay.games.rushHour.RushHour.launch(RushHour.java:2423)
2019-04-02 10:04:06,695 ERROR - 	at net.gazeplay.GameMenuFactory.chooseGame(GameMenuFactory.java:373)
2019-04-02 10:04:06,696 ERROR - 	at net.gazeplay.GameMenuFactory.access$3(GameMenuFactory.java:332)
2019-04-02 10:04:06,696 ERROR - 	at net.gazeplay.GameMenuFactory$1.handle(GameMenuFactory.java:255)
2019-04-02 10:04:06,696 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-04-02 10:04:06,696 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-04-02 10:04:06,696 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-04-02 10:04:06,696 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-04-02 10:04:06,696 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-02 10:04:06,697 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-04-02 10:04:06,698 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-02 10:04:06,698 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-04-02 10:04:06,698 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-04-02 10:04:06,698 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-04-02 10:04:06,698 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-04-02 10:04:06,698 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2019-04-02 10:04:06,698 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2019-04-02 10:04:06,698 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-04-02 10:04:06,698 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-04-02 10:04:06,699 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-04-02 10:04:06,699 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
2019-04-02 10:04:06,699 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-04-02 10:04:06,699 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-04-02 10:04:06,699 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
2019-04-02 10:04:06,699 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-04-02 10:04:06,699 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
2019-04-02 10:04:06,699 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-04-02 10:04:06,699 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2019-04-02 10:04:06,700 ERROR - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2019-04-02 10:04:06,700 ERROR - 	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
2019-04-02 10:04:06,700 ERROR - 	at java.lang.Thread.run(Thread.java:748)

**Comment by johzz-o2** [comment]
this is fixed
