### ISSUE TITLE
exception in where is the color

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#687]
occured only once,

By clicking home button during congratulations in the where is the color game :

`   2019-04-02 09:44:17,272 ERROR - java.lang.InterruptedException: sleep interrupted
2019-04-02 09:44:17,273 ERROR - 	at java.lang.Thread.sleep(Native Method)
2019-04-02 09:44:17,273 ERROR - 	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager$1$1.call(TobiiGazeDeviceManager.java:69)
2019-04-02 09:44:17,273 ERROR - 	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager$1$1.call(TobiiGazeDeviceManager.java:1)
2019-04-02 09:44:17,273 ERROR - 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
2019-04-02 09:44:17,273 ERROR - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-04-02 09:44:17,273 INFO  - outputDirectoryCreated = true
2019-04-02 09:44:17,273 ERROR - 	at javafx.concurrent.Service.lambda$null$493(Service.java:725)
2019-04-02 09:44:17,273 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-04-02 09:44:17,274 INFO  - Heatmap size: 400 X 250
2019-04-02 09:44:17,274 ERROR - 	at javafx.concurrent.Service.lambda$executeTask$494(Service.java:724)
2019-04-02 09:44:17,274 ERROR - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-04-02 09:44:17,274 ERROR - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-04-02 09:44:17,275 ERROR - 	at java.lang.Thread.run(Thread.java:748)
2019-04-02 09:44:17,281 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: 4
2019-04-02 09:44:17,281 ERROR - 	at net.gazeplay.commons.utils.HeatMap.getColor(HeatMap.java:112)
2019-04-02 09:44:17,281 ERROR - 	at net.gazeplay.commons.utils.HeatMap.<init>(HeatMap.java:89)
2019-04-02 09:44:17,281 ERROR - 	at net.gazeplay.commons.utils.HeatMap.<init>(HeatMap.java:52)
2019-04-02 09:44:17,281 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveHeatMapAsPng(Stats.java:226)
2019-04-02 09:44:17,281 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveStats(Stats.java:123)
2019-04-02 09:44:17,281 ERROR - 	at net.gazeplay.commons.utils.stats.HiddenItemsGamesStats.saveStats(HiddenItemsGamesStats.java:18)
2019-04-02 09:44:17,281 ERROR - 	at net.gazeplay.GameContext.lambda$9(GameContext.java:397)
2019-04-02 09:44:17,281 ERROR - 	at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:406)
2019-04-02 09:44:17,282 ERROR - 	at net.gazeplay.GameContext.lambda$7(GameContext.java:350)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-04-02 09:44:17,282 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-04-02 09:44:17,283 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-04-02 09:44:17,283 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-04-02 09:44:17,283 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2019-04-02 09:44:17,283 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2019-04-02 09:44:17,283 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-04-02 09:44:17,283 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-04-02 09:44:17,283 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-04-02 09:44:17,283 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
2019-04-02 09:44:17,283 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-04-02 09:44:17,284 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-04-02 09:44:17,284 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
2019-04-02 09:44:17,284 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-04-02 09:44:17,284 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
2019-04-02 09:44:17,284 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-04-02 09:44:17,284 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2019-04-02 09:44:17,284 ERROR - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2019-04-02 09:44:17,284 ERROR - 	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
2019-04-02 09:44:17,284 ERROR - 	at java.lang.Thread.run(Thread.java:748)  `

**Comment by teoblachere** [comment]
Looks like this is the same error reported in #705 which I fixed (hopefully) in #712 
Should be fine now
