### ISSUE TITLE
Error on Exiting games

### ISSUE THREAD

**Issue by wafaahs** [schwabdidier/GazePlay#705]
I am getting the following error when attempting to exit games. It happened twice today, but I'm not sure what triggered it. 

2019-04-11 19:13:24,427 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: 4
2019-04-11 19:13:24,428 ERROR - 	at net.gazeplay.commons.utils.HeatMap.getColor(HeatMap.java:112)
2019-04-11 19:13:24,428 ERROR - 	at net.gazeplay.commons.utils.HeatMap.<init>(HeatMap.java:89)
2019-04-11 19:13:24,428 ERROR - 	at net.gazeplay.commons.utils.HeatMap.<init>(HeatMap.java:52)
2019-04-11 19:13:24,428 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveHeatMapAsPng(Stats.java:226)
2019-04-11 19:13:24,428 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveStats(Stats.java:123)
2019-04-11 19:13:24,428 ERROR - 	at net.gazeplay.games.math101.MathGamesStats.saveStats(MathGamesStats.java:20)
2019-04-11 19:13:24,428 ERROR - 	at net.gazeplay.GameContext.lambda$homeButtonClicked$9(GameContext.java:397)
2019-04-11 19:13:24,429 ERROR - 	at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:406)
2019-04-11 19:13:24,429 ERROR - 	at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$7(GameContext.java:350)
2019-04-11 19:13:24,429 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-04-11 19:13:24,429 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-04-11 19:13:24,429 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-04-11 19:13:24,429 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-04-11 19:13:24,429 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-04-11 19:13:24,429 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-04-11 19:13:24,429 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-11 19:13:24,430 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-04-11 19:13:24,430 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-11 19:13:24,430 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-04-11 19:13:24,430 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-04-11 19:13:24,430 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-04-11 19:13:24,430 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-04-11 19:13:24,430 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-04-11 19:13:24,430 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-04-11 19:13:24,430 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2019-04-11 19:13:24,430 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2019-04-11 19:13:24,430 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-04-11 19:13:24,431 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-04-11 19:13:24,431 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-04-11 19:13:24,431 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
2019-04-11 19:13:24,431 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-04-11 19:13:24,431 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-04-11 19:13:24,431 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
2019-04-11 19:13:24,431 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-04-11 19:13:24,431 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
2019-04-11 19:13:24,431 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-04-11 19:13:24,431 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by teoblachere** [comment]
Happened to me once before, thought it was a fluke since I was messing with my game. I'll try to recreate the bug/error, and try to find out why it messes up.

**Comment by teoblachere** [comment]
I wasn't able to produce the error again, but I did modify the color picking loop so it shouldn't bug again.
If it does though, I added a log message with the values used while creating the heatmap, so if anyone encounters this error again, please send me that log.
