### ISSUE TITLE
Error on Exiting Game - Fixation Sequence

### ISSUE THREAD

**Issue by wafaahs** [schwabdidier/GazePlay#724]
I came across the following error while exiting a game.. pasting it here for later reference: 

2019-05-21 17:42:46,687 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArithmeticException: integer overflow
2019-05-21 17:42:46,688 ERROR - 	at java.lang.Math.toIntExact(Math.java:1011)
2019-05-21 17:42:46,688 ERROR - 	at net.gazeplay.commons.utils.FixationSequence.<init>(FixationSequence.java:95)
2019-05-21 17:42:46,688 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveFixationSequenceAsPng(Stats.java:320)
2019-05-21 17:42:46,688 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveStats(Stats.java:198)
2019-05-21 17:42:46,688 ERROR - 	at net.gazeplay.commons.utils.stats.ShootGamesStats.saveStats(ShootGamesStats.java:19)
2019-05-21 17:42:46,688 ERROR - 	at net.gazeplay.GameContext.lambda$homeButtonClicked$9(GameContext.java:414)
2019-05-21 17:42:46,688 ERROR - 	at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:423)
2019-05-21 17:42:46,688 ERROR - 	at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$7(GameContext.java:363)
2019-05-21 17:42:46,688 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-05-21 17:42:46,688 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-05-21 17:42:46,688 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-05-21 17:42:46,688 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-05-21 17:42:46,689 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-05-21 17:42:46,689 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-05-21 17:42:46,689 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-21 17:42:46,689 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-21 17:42:46,689 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-21 17:42:46,689 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-21 17:42:46,689 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-21 17:42:46,689 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-05-21 17:42:46,690 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-05-21 17:42:46,690 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-05-21 17:42:46,690 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-05-21 17:42:46,690 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2019-05-21 17:42:46,690 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2019-05-21 17:42:46,690 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-05-21 17:42:46,690 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-05-21 17:42:46,690 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-05-21 17:42:46,690 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
2019-05-21 17:42:46,690 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-05-21 17:42:46,690 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-05-21 17:42:46,690 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
2019-05-21 17:42:46,690 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-05-21 17:42:46,690 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
2019-05-21 17:42:46,690 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-05-21 17:42:46,690 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by schwabdidier** [comment]
done
