### ISSUE TITLE
Error with Tobii 

### ISSUE THREAD

**Issue by johzz-o2** [schwabdidier/GazePlay#738]
while trying the games today with Tobii I got the following errors : 
2019-05-24 15:19:33,801 ERROR - java.lang.UnsatisfiedLinkError: C:\Users\Johana\AppData\Local\TobiiStreamEngineForJava\lib\tobii\x64\tobii_jni_stream_engine.dll: Can't find dependent libraries
2019-05-24 15:19:33,801 ERROR - 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
2019-05-24 15:19:33,801 ERROR - 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
2019-05-24 15:19:33,801 ERROR - 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
2019-05-24 15:19:33,802 ERROR - 	at java.lang.Runtime.load0(Runtime.java:809)
2019-05-24 15:19:33,802 ERROR - 	at java.lang.System.load(System.java:1086)
2019-05-24 15:19:33,802 ERROR - 	at tobii.Tobii.loadLibrary(Tobii.java:78)
2019-05-24 15:19:33,802 ERROR - 	at tobii.Tobii.loadNeededLibraries(Tobii.java:61)
2019-05-24 15:19:33,802 ERROR - 	at tobii.Tobii.loadIfNotLoaded(Tobii.java:40)
2019-05-24 15:19:33,802 ERROR - 	at tobii.Tobii.gazePosition(Tobii.java:22)
2019-05-24 15:19:33,802 ERROR - 	at net.gazeplay.commons.gaze.devicemanager.TobiiGazeDeviceManager.init(TobiiGazeDeviceManager.java:29)
2019-05-24 15:19:33,802 ERROR - 	at net.gazeplay.commons.gaze.devicemanager.GazeDeviceManagerFactory.createNewGazeListener(GazeDeviceManagerFactory.java:51)
2019-05-24 15:19:33,803 ERROR - 	at net.gazeplay.HomeMenuScreen.<init>(HomeMenuScreen.java:78)
2019-05-24 15:19:33,803 ERROR - 	at net.gazeplay.HomeMenuScreen.newInstance(HomeMenuScreen.java:60)
2019-05-24 15:19:33,803 ERROR - 	at net.gazeplay.GazePlay.start(GazePlay.java:85)
2019-05-24 15:19:33,803 ERROR - 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$166(LauncherImpl.java:863)
2019-05-24 15:19:33,803 ERROR - 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$179(PlatformImpl.java:326)
2019-05-24 15:19:33,803 ERROR - 	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
2019-05-24 15:19:33,803 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-05-24 15:19:33,804 ERROR - 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
2019-05-24 15:19:33,804 ERROR - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2019-05-24 15:19:33,804 ERROR - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2019-05-24 15:19:33,804 ERROR - 	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
2019-05-24 15:19:33,804 ERROR - 	at java.lang.Thread.run(Thread.java:748)

**Comment by schwabdidier** [comment]
Please see issue 161

**Comment by schwabdidier** [comment]
Please see issue @161
