### ISSUE TITLE
Exception in Sliding Puzzles

### ISSUE THREAD

**Issue by johzz-o2** [schwabdidier/GazePlay#747]
I got this error after trying the last version of the game. 

2019-05-28 09:57:24,930 ERROR - Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
2019-05-28 09:57:24,930 ERROR - 	at com.sun.javafx.scene.control.skin.SliderSkin.lambda$initialize$576(SliderSkin.java:140)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-05-28 09:57:24,931 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-05-28 09:57:24,931 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-05-28 09:57:24,931 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
2019-05-28 09:57:24,932 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-05-28 09:57:24,932 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-05-28 09:57:24,932 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-05-28 09:57:24,932 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$345(GlassViewEventHandler.java:432)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
2019-05-28 09:57:24,932 ERROR - 	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139)
2019-05-28 09:57:24,932 ERROR - 	at java.lang.Thread.run(Thread.java:748)

**Comment by johzz-o2** [comment]
@petinhoss7

**Comment by petinhoss7** [comment]
This exception is not showing on my macbook in the latest version , maybe you can try again with the newest update.
