### ISSUE TITLE
Spot the difference Game not working on my Mac

### ISSUE THREAD

**Issue by petinhoss7** [schwabdidier/GazePlay#753]
This is the error displayed :
java.io.FileNotFoundException: file:/Users/admin/.m2/repository/com/github/schwabdidier/gazeplay-data/1.5.2-SNAPSHOT/gazeplay-data-1.5.2-SNAPSHOT.jar!/data/spotthedifferences/instances.json (No such file or directory)
2019-05-29 10:37:51,541 ERROR - 	at java.io.FileInputStream.open0(Native Method)
2019-05-29 10:37:51,542 ERROR - 	at java.io.FileInputStream.open(FileInputStream.java:195)
2019-05-29 10:37:51,543 ERROR - 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
2019-05-29 10:37:51,543 ERROR - 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
2019-05-29 10:37:51,544 ERROR - 	at net.gazeplay.games.spotthedifferences.SpotTheDifferences.<init>(SpotTheDifferences.java:115)
2019-05-29 10:37:51,544 ERROR - 	at net.gazeplay.DefaultGamesLocator$74.createNewGame(DefaultGamesLocator.java:1153)
2019-05-29 10:37:51,544 ERROR - 	at net.gazeplay.GameMenuFactory.chooseGame(GameMenuFactory.java:354)
2019-05-29 10:37:51,544 ERROR - 	at net.gazeplay.GameMenuFactory.access$200(GameMenuFactory.java:37)
2019-05-29 10:37:51,544 ERROR - 	at net.gazeplay.GameMenuFactory$1.handle(GameMenuFactory.java:254)
2019-05-29 10:37:51,544 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-05-29 10:37:51,545 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-05-29 10:37:51,545 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-05-29 10:37:51,545 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-05-29 10:37:51,545 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-05-29 10:37:51,545 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-05-29 10:37:51,545 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,546 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-29 10:37:51,546 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,546 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-29 10:37:51,546 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,546 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-29 10:37:51,546 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,547 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-29 10:37:51,547 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,548 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-05-29 10:37:51,548 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-05-29 10:37:51,549 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-05-29 10:37:51,549 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-05-29 10:37:51,549 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2019-05-29 10:37:51,550 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2019-05-29 10:37:51,550 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-05-29 10:37:51,550 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-05-29 10:37:51,550 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-05-29 10:37:51,550 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
2019-05-29 10:37:51,550 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-05-29 10:37:51,551 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-05-29 10:37:51,551 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
2019-05-29 10:37:51,551 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-05-29 10:37:51,551 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
2019-05-29 10:37:51,551 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-05-29 10:37:51,551 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2019-05-29 10:37:51,556 INFO  - Music panel created
2019-05-29 10:37:51,560 INFO  - the speed of the effects is = 4.0
2019-05-29 10:37:51,616 INFO  - heatMapWidth = 250, heatMapHeight = 400
2019-05-29 10:37:51,662 WARN  - Nodes not removed: 0
2019-05-29 10:37:51,663 ERROR - Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
2019-05-29 10:37:51,664 ERROR - 	at net.gazeplay.games.spotthedifferences.SpotTheDifferences.launch(SpotTheDifferences.java:155)
2019-05-29 10:37:51,664 ERROR - 	at net.gazeplay.GameMenuFactory.chooseGame(GameMenuFactory.java:372)
2019-05-29 10:37:51,664 ERROR - 	at net.gazeplay.GameMenuFactory.access$200(GameMenuFactory.java:37)
2019-05-29 10:37:51,664 ERROR - 	at net.gazeplay.GameMenuFactory$1.handle(GameMenuFactory.java:254)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,664 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-05-29 10:37:51,665 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-05-29 10:37:51,665 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-05-29 10:37:51,665 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2019-05-29 10:37:51,665 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2019-05-29 10:37:51,665 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-05-29 10:37:51,665 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-05-29 10:37:51,665 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-05-29 10:37:51,665 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-05-29 10:37:51,665 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
2019-05-29 10:37:51,666 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-05-29 10:37:51,666 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2019-05-29 10:37:54,976 WARN  - Nodes not removed: 0
2019-05-29 10:37:54,979 ERROR - Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
2019-05-29 10:37:54,980 ERROR - 	at net.gazeplay.games.spotthedifferences.SpotTheDifferences.launch(SpotTheDifferences.java:155)
2019-05-29 10:37:54,981 ERROR - 	at net.gazeplay.games.spotthedifferences.SpotTheDifferences.lambda$new$0(SpotTheDifferences.java:108)
2019-05-29 10:37:54,981 ERROR - 	at net.gazeplay.commons.utils.ProgressButton$1$1.handle(ProgressButton.java:130)
2019-05-29 10:37:54,982 ERROR - 	at net.gazeplay.commons.utils.ProgressButton$1$1.handle(ProgressButton.java:125)
2019-05-29 10:37:54,983 ERROR - 	at javafx.animation.Animation.impl_finished(Animation.java:1132)
2019-05-29 10:37:54,983 ERROR - 	at javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
2019-05-29 10:37:54,983 ERROR - 	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
2019-05-29 10:37:54,984 ERROR - 	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
2019-05-29 10:37:54,985 ERROR - 	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
2019-05-29 10:37:54,986 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-05-29 10:37:54,986 ERROR - 	at javafx.animation.Animation$1.timePulse(Animation.java:185)
2019-05-29 10:37:54,987 ERROR - 	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
2019-05-29 10:37:54,987 ERROR - 	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
2019-05-29 10:37:54,988 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
2019-05-29 10:37:54,988 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
2019-05-29 10:37:54,988 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
2019-05-29 10:37:54,989 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)

**Comment by teoblachere** [comment]
Is this still an issue? Or did my patch work?

**Comment by petinhoss7** [comment]
Problem solved , It worked .
