### ISSUE TITLE
Exception thrown when exiting Blocks game

### ISSUE THREAD

**Issue by petinhoss7** [schwabdidier/GazePlay#776]
2019-06-06 21:33:09,290 ERROR - java.lang.RuntimeException: Requested texture dimension (20032) requires dimension (0) that exceeds maximum texture size (16384)
2019-06-06 21:33:09,290 ERROR - 	at com.sun.prism.es2.ES2RTTexture.getCompatibleDimension(ES2RTTexture.java:135)
2019-06-06 21:33:09,290 ERROR - 	at com.sun.prism.es2.ES2ResourceFactory.getRTTWidth(ES2ResourceFactory.java:145)
2019-06-06 21:33:09,290 ERROR - 	at com.sun.scenario.effect.impl.prism.ps.PPSDrawable.getCompatibleWidth(PPSDrawable.java:48)
2019-06-06 21:33:09,290 ERROR - 	at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.getCompatibleWidth(PPSRenderer.java:153)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.scenario.effect.impl.ImagePool.checkOut(ImagePool.java:119)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.scenario.effect.impl.Renderer.getCompatibleImage(Renderer.java:116)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.getCompatibleImage(PPSRenderer.java:168)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.getCompatibleImage(PPSRenderer.java:67)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.scenario.effect.Effect.getCompatibleImage(Effect.java:479)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.javafx.sg.prism.NGCanvas$RenderInput.filter(NGCanvas.java:1582)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:185)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.javafx.sg.prism.NGCanvas.applyEffectOnAintoC(NGCanvas.java:737)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.javafx.sg.prism.NGCanvas.renderStream(NGCanvas.java:1080)
2019-06-06 21:33:09,291 ERROR - 	at com.sun.javafx.sg.prism.NGCanvas.renderContent(NGCanvas.java:606)
2019-06-06 21:33:09,292 ERROR - 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
2019-06-06 21:33:09,292 ERROR - 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
2019-06-06 21:33:09,292 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit$5.draw(QuantumToolkit.java:1400)
2019-06-06 21:33:09,292 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit$5.run(QuantumToolkit.java:1436)
2019-06-06 21:33:09,292 ERROR - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2019-06-06 21:33:09,292 ERROR - 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2019-06-06 21:33:09,292 ERROR - 	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
2019-06-06 21:33:09,292 ERROR - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-06-06 21:33:09,292 ERROR - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-06-06 21:33:09,292 ERROR - 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
2019-06-06 21:33:09,292 ERROR - 	at java.lang.Thread.run(Thread.java:748)
2019-06-06 21:33:09,293 ERROR - Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Unrecognized image loader: null
2019-06-06 21:33:09,293 ERROR - 	at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:240)
2019-06-06 21:33:09,293 ERROR - 	at javafx.scene.image.WritableImage.access$000(WritableImage.java:46)
2019-06-06 21:33:09,293 ERROR - 	at javafx.scene.image.WritableImage$1.loadTkImage(WritableImage.java:51)
2019-06-06 21:33:09,293 ERROR - 	at javafx.scene.Scene.doSnapshot(Scene.java:1236)
2019-06-06 21:33:09,293 ERROR - 	at javafx.scene.Node.doSnapshot(Node.java:1862)
2019-06-06 21:33:09,294 ERROR - 	at javafx.scene.Node.snapshot(Node.java:1940)
2019-06-06 21:33:09,294 ERROR - 	at net.gazeplay.commons.utils.FixationSequence.<init>(FixationSequence.java:104)
2019-06-06 21:33:09,294 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveFixationSequenceAsPng(Stats.java:403)
2019-06-06 21:33:09,294 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveStats(Stats.java:253)
2019-06-06 21:33:09,294 ERROR - 	at net.gazeplay.commons.utils.stats.HiddenItemsGamesStats.saveStats(HiddenItemsGamesStats.java:18)
2019-06-06 21:33:09,294 ERROR - 	at net.gazeplay.GameContext.lambda$homeButtonClicked$9(GameContext.java:408)
2019-06-06 21:33:09,294 ERROR - 	at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:417)
2019-06-06 21:33:09,294 ERROR - 	at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$7(GameContext.java:356)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-06-06 21:33:09,294 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-06-06 21:33:09,295 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-06-06 21:33:09,295 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-06-06 21:33:09,295 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2019-06-06 21:33:09,295 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2019-06-06 21:33:09,295 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-06-06 21:33:09,295 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-06-06 21:33:09,295 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-06-06 21:33:09,295 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-06-06 21:33:09,295 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
2019-06-06 21:33:09,296 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-06-06 21:33:09,296 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by schwabdidier** [comment]
The error still exists

**Comment by schwabdidier** [comment]
Error is caused with line 

`canvas.snapshot(params, image);` in FixationSequence.java
