### ISSUE TITLE
Java Heap Space Error

### ISSUE THREAD

**Issue by wafaahs** [schwabdidier/GazePlay#778]
I am facing this error a lot when I attempt to use the game. But I noticed today that it is especially the case when I try to select/unselect the categories filters:

2019-06-11 14:37:54,662 ERROR - Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: Java heap space
2019-06-11 14:37:54,662 ERROR - 	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
2019-06-11 14:37:54,662 ERROR - 	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
2019-06-11 14:37:54,663 ERROR - 	at com.sun.javafx.iio.png.PNGImageLoader2.load(PNGImageLoader2.java:652)
2019-06-11 14:37:54,663 ERROR - 	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:364)
2019-06-11 14:37:54,663 ERROR - 	at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:324)
2019-06-11 14:37:54,663 ERROR - 	at com.sun.javafx.tk.quantum.PrismImageLoader2.loadAll(PrismImageLoader2.java:127)
2019-06-11 14:37:54,663 ERROR - 	at com.sun.javafx.tk.quantum.PrismImageLoader2.<init>(PrismImageLoader2.java:71)
2019-06-11 14:37:54,663 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.loadImage(QuantumToolkit.java:720)
2019-06-11 14:37:54,663 ERROR - 	at javafx.scene.image.Image.loadImage(Image.java:1065)
2019-06-11 14:37:54,663 ERROR - 	at javafx.scene.image.Image.initialize(Image.java:807)
2019-06-11 14:37:54,663 ERROR - 	at javafx.scene.image.Image.<init>(Image.java:621)
2019-06-11 14:37:54,663 ERROR - 	at net.gazeplay.commons.utils.CustomButton.<init>(CustomButton.java:22)
2019-06-11 14:37:54,663 ERROR - 	at net.gazeplay.HomeMenuScreen.createLogoutButton(HomeMenuScreen.java:337)
2019-06-11 14:37:54,664 ERROR - 	at net.gazeplay.HomeMenuScreen.<init>(HomeMenuScreen.java:81)
2019-06-11 14:37:54,664 ERROR - 	at net.gazeplay.HomeMenuScreen.newInstance(HomeMenuScreen.java:60)
2019-06-11 14:37:54,664 ERROR - 	at net.gazeplay.HomeMenuScreen$1.handle(HomeMenuScreen.java:130)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:282)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:223)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-06-11 14:37:54,664 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-06-11 14:37:54,665 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-06-11 14:37:54,665 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-06-11 14:37:54,665 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-06-11 14:37:54,665 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-06-11 14:37:54,665 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-06-11 14:37:54,665 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)

**Comment by johzz-o2** [comment]
@wafaahs  which game ?

**Comment by wafaahs** [comment]
@johzz-o2 No specific game. This extract was from when I checked/unckecked the game categories multiple times in the main menu to view each set of games on its own

**Comment by petinhoss7** [comment]
i tried to check/uncheck game categories and all seems ok for me , maybe it's specific to your computer

**Comment by johzz-o2** [comment]
@wafaahs  I just checked also and I don't encounter this problem. Maybe it has to do with your computer

**Comment by wafaahs** [comment]
Again.. this happened several times and not just from this action
And yes the reason might be that my laptop's memory is not big enough.. which might be the case for our users as well...
So it is possible that some memory management needs to added in general for the whole platform
Which is why I added this issue

**Comment by johzz-o2** [comment]
Very well, If you could add the cases when you encountered this issue it would be helpful to adjust it. I just found it odd to be a result from the check/unchecking part.

**Comment by wafaahs** [comment]
I will add them as soon as I encounter it again with the specific steps that caused it! No worries.
I'm just focusing on testing parts of the game that are unlikely to cause the same issue for now.

**Comment by kuhlkrein** [comment]
Hey, you should check #566 , sometimes, increasing the size of the heap is enougth

**Comment by johzz-o2** [comment]
This error reproduced after I added the 4th category . From checking/unchecking frequently the categories of the game. I'll try a new approach to display the list of games, and hopefully avoid this error.

**Comment by schwabdidier** [comment]
we have a problem with this menu, we will make that in another way
