### ISSUE TITLE
various bugs in zip version

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#798]
@johzz-o2 @teoblachere . Please check zip version (gazeplay-dist/target/gazeplay-dist-1.5.2-SNAPSHOT) on Windows.

Several games don't work (potion, goose, slidding puzzle for instance), there are some problems in jar files.

We need to resolve that before release. It is top priority.

**Comment by teoblachere** [comment]
![image](https://user-images.githubusercontent.com/19331032/60420158-50fcb480-9be7-11e9-856a-1f0d66f9348a.png)

Found this bug in sliding puzzle, the square doesn't slide all the way to the center, I'm on it

**Comment by johzz-o2** [comment]
Bug in Magic Potions ( possibility of simultaneous selection ) . Taking care of it .

**Comment by johzz-o2** [comment]
In the Space Game , the space ship doesn't move smoothly and also it's movement is restricted . It never extends to the width of the screen.

**Comment by schwabdidier** [comment]
Yes, Malia, my daughter, did not like it either. I add an issue about it.

**Comment by johzz-o2** [comment]
Rush Hour Exception : 
2019-07-01 12:47:54,973 ERROR - Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
2019-07-01 12:47:54,973 ERROR - 	at net.gazeplay.games.rushHour.RushHour.lambda$setLevel$2(RushHour.java:86)
2019-07-01 12:47:54,973 ERROR - 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
2019-07-01 12:47:54,974 ERROR - 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
2019-07-01 12:47:54,974 ERROR - 	at javafx.beans.property.IntegerPropertyBase.fireValueChangedEvent(IntegerPropertyBase.java:106)
2019-07-01 12:47:54,974 ERROR - 	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
2019-07-01 12:47:54,974 ERROR - 	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
2019-07-01 12:47:54,974 ERROR - 	at net.gazeplay.games.rushHour.RushHour.setLevel0(RushHour.java:186)
2019-07-01 12:47:54,974 ERROR - 	at net.gazeplay.games.rushHour.RushHour.setLevel(RushHour.java:98)
2019-07-01 12:47:54,974 ERROR - 	at net.gazeplay.games.rushHour.RushHour.launch(RushHour.java:2423)
2019-07-01 12:47:54,974 ERROR - 	at net.gazeplay.GameMenuFactory.chooseGame(GameMenuFactory.java:374)
2019-07-01 12:47:54,974 ERROR - 	at net.gazeplay.GameMenuFactory.access$200(GameMenuFactory.java:37)
2019-07-01 12:47:54,975 ERROR - 	at net.gazeplay.GameMenuFactory$1.handle(GameMenuFactory.java:254)
2019-07-01 12:47:54,975 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-07-01 12:47:54,975 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-07-01 12:47:54,975 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-07-01 12:47:54,975 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-07-01 12:47:54,975 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-07-01 12:47:54,975 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-07-01 12:47:54,976 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-01 12:47:54,976 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-07-01 12:47:54,976 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-01 12:47:54,976 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-07-01 12:47:54,976 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-01 12:47:54,976 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-07-01 12:47:54,976 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-01 12:47:54,976 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-07-01 12:47:54,977 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-01 12:47:54,977 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-07-01 12:47:54,977 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-07-01 12:47:54,977 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-07-01 12:47:54,977 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2019-07-01 12:47:54,977 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2019-07-01 12:47:54,977 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2019-07-01 12:47:54,977 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2019-07-01 12:47:54,978 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-07-01 12:47:54,978 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2019-07-01 12:47:54,978 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
2019-07-01 12:47:54,978 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2019-07-01 12:47:54,978 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-07-01 12:47:54,978 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$345(GlassViewEventHandler.java:432)
2019-07-01 12:47:54,978 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2019-07-01 12:47:54,978 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
2019-07-01 12:47:54,978 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-07-01 12:47:54,979 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2019-07-01 12:47:54,979 ERROR - 	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
2019-07-01 12:47:54,979 ERROR - 	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139)
2019-07-01 12:47:54,979 ERROR - 	at java.lang.Thread.run(Thread.java:748)

**Comment by johzz-o2** [comment]
The colors of the cars in Rush Hour have "disappeared" . Now all the cars / except the Taxi are in a brownish / burgundy color .

**Comment by schwabdidier** [comment]
No, it is not a bug

**Comment by johzz-o2** [comment]
oh , I see . I'm sorry 😞

**Comment by schwabdidier** [comment]
resolved
