### ISSUE TITLE
ArrayIndexOutOfBoundsException error in ScratchCards

### ISSUE THREAD

**Issue by teoblachere** [schwabdidier/GazePlay#808]
Seems to happen when the biboule celebration animation is launched.
It makes the game freeze for a short moment.

Traceback:
Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1591)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1535)
	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388)
	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
	at javafx.scene.Node.updateGeomBounds(Node.java:3577)
	at javafx.scene.Node.getGeomBounds(Node.java:3530)
	at javafx.scene.Node.getLocalBounds(Node.java:3478)
	at javafx.scene.Node.updateTxBounds(Node.java:3641)
	at javafx.scene.Node.getTransformedBounds(Node.java:3424)
	at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1732)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1596)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1535)
	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388)
	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
	at javafx.scene.Node.updateGeomBounds(Node.java:3577)
	at javafx.scene.Node.getGeomBounds(Node.java:3530)
	at javafx.scene.Node.getLocalBounds(Node.java:3478)
	at javafx.scene.Node.impl_intersectsBounds(Node.java:5013)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2931)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3899)
	at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3485)
	at javafx.scene.Scene.pick(Scene.java:1942)
	at javafx.scene.Scene.access$6700(Scene.java:159)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3711)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)

**Comment by teoblachere** [comment]
java.lang.NullPointerException
2019-07-03 10:44:57,923 ERROR - 	at com.sun.prism.impl.ps.BaseShaderGraphics.setPaint(BaseShaderGraphics.java:113)
2019-07-03 10:44:57,923 ERROR - 	at com.sun.javafx.sg.prism.NGShape.renderContent2D(NGShape.java:287)
2019-07-03 10:44:57,923 ERROR - 	at com.sun.javafx.sg.prism.NGShape.renderContent(NGShape.java:261)
2019-07-03 10:44:57,924 ERROR - 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
2019-07-03 10:44:57,924 ERROR - 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
2019-07-03 10:44:57,924 ERROR - 	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
2019-07-03 10:44:57,924 ERROR - 	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
2019-07-03 10:44:57,924 ERROR - 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
2019-07-03 10:44:57,924 ERROR - 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
2019-07-03 10:44:57,924 ERROR - 	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
2019-07-03 10:44:57,925 ERROR - 	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
2019-07-03 10:44:57,925 ERROR - 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
2019-07-03 10:44:57,925 ERROR - 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
2019-07-03 10:44:57,925 ERROR - 	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
2019-07-03 10:44:57,925 ERROR - 	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
2019-07-03 10:44:57,925 ERROR - 	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
2019-07-03 10:44:57,925 ERROR - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2019-07-03 10:44:57,925 ERROR - 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2019-07-03 10:44:57,925 ERROR - 	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
2019-07-03 10:44:57,925 ERROR - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-07-03 10:44:57,925 ERROR - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-07-03 10:44:57,925 ERROR - 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
2019-07-03 10:44:57,925 ERROR - 	at java.lang.Thread.run(Thread.java:748)
