### ISSUE TITLE
Exception when game is not played

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#836]
`2019-07-20 16:00:57,737 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2019-07-20 16:00:57,737 ERROR - 	at java.util.ArrayList.elementData(ArrayList.java:418)
2019-07-20 16:00:57,737 ERROR - 	at java.util.ArrayList.get(ArrayList.java:431)
2019-07-20 16:00:57,737 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.setTargetAOIList(Stats.java:116)
2019-07-20 16:00:57,737 ERROR - 	at net.gazeplay.games.creampie.CreamPie.dispose(CreamPie.java:53)
2019-07-20 16:00:57,737 ERROR - 	at net.gazeplay.GameContext.exitGame(GameContext.java:437)
2019-07-20 16:00:57,737 ERROR - 	at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$22(GameContext.java:422)
2019-07-20 16:00:57,737 ERROR - 	at net.gazeplay.GameContext$$Lambda$377/1752208284.handle(Unknown Source)
2019-07-20 16:00:57,737 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-07-20 16:00:57,737 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-07-20 16:00:57,737 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-07-20 16:00:57,738 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-07-20 16:00:57,738 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3471)
2019-07-20 16:00:57,738 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3399)
2019-07-20 16:00:57,738 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3767)
2019-07-20 16:00:57,738 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
2019-07-20 16:00:57,738 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-07-20 16:00:57,738 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
2019-07-20 16:00:57,738 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
2019-07-20 16:00:57,739 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-07-20 16:00:57,739 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
2019-07-20 16:00:57,739 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$282/1365869545.get(Unknown Source)
2019-07-20 16:00:57,739 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
2019-07-20 16:00:57,739 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
2019-07-20 16:00:57,739 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-07-20 16:00:57,739 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:927)

Process finished with exit code 0`

**Comment by schwabdidier** [comment]
occurs at least in cream pie
