### ISSUE TITLE
Bug when exiting Horses

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#841]
`2019-07-21 11:21:00,263 INFO  - outputDirectoryCreated = true
2019-07-21 11:21:01,610 ERROR - Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Children: duplicate children added: parent = Pane@696efa96
2019-07-21 11:21:01,611 ERROR - 	at javafx.scene.Parent$2.onProposedChange(Parent.java:451)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.collections.VetoableListDecorator.clear(VetoableListDecorator.java:294)
2019-07-21 11:21:01,611 ERROR - 	at net.gazeplay.GraphicalContext.clear(GraphicalContext.java:119)
2019-07-21 11:21:01,611 ERROR - 	at net.gazeplay.GameContext.exitGame(GameContext.java:459)
2019-07-21 11:21:01,611 ERROR - 	at net.gazeplay.GameContext.lambda$createHomeButtonInGameScreen$22(GameContext.java:422)
2019-07-21 11:21:01,611 ERROR - 	at net.gazeplay.GameContext$$Lambda$395/305966959.handle(Unknown Source)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2019-07-21 11:21:01,611 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2019-07-21 11:21:01,611 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2019-07-21 11:21:01,611 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3471)
2019-07-21 11:21:01,612 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3399)
2019-07-21 11:21:01,612 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3767)
2019-07-21 11:21:01,612 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
2019-07-21 11:21:01,612 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-07-21 11:21:01,612 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
2019-07-21 11:21:01,612 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
2019-07-21 11:21:01,612 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
2019-07-21 11:21:01,612 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-07-21 11:21:01,612 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
2019-07-21 11:21:01,612 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$284/710729747.get(Unknown Source)
2019-07-21 11:21:01,612 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
2019-07-21 11:21:01,612 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
2019-07-21 11:21:01,612 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-07-21 11:21:01,612 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:927)`

**Comment by schwabdidier** [comment]
done
