### ISSUE TITLE
Bug when scratch card is completed

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#870]
2019-08-26 22:25:58,216 DEBUG - Adding task to JavaFX thread queue ...
2019-08-26 22:25:58,220 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2019-08-26 22:25:58,221 ERROR - 	at java.util.ArrayList.elementData(ArrayList.java:418)
2019-08-26 22:25:58,221 ERROR - 	at java.util.ArrayList.get(ArrayList.java:431)
2019-08-26 22:25:58,221 ERROR - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1580)
2019-08-26 22:25:58,221 ERROR - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
2019-08-26 22:25:58,221 ERROR - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1377)
2019-08-26 22:25:58,221 ERROR - 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
2019-08-26 22:25:58,221 ERROR - 	at javafx.scene.Node.updateGeomBounds(Node.java:3556)
2019-08-26 22:25:58,221 ERROR - 	at javafx.scene.Node.getGeomBounds(Node.java:3509)
2019-08-26 22:25:58,221 ERROR - 	at javafx.scene.Node.getLocalBounds(Node.java:3457)
2019-08-26 22:25:58,221 ERROR - 	at javafx.scene.Node.updateTxBounds(Node.java:3620)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Node.getTransformedBounds(Node.java:3403)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1721)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1585)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1377)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Node.updateGeomBounds(Node.java:3556)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Node.getGeomBounds(Node.java:3509)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Node.getLocalBounds(Node.java:3457)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Node.impl_intersectsBounds(Node.java:4992)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2931)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Node.impl_pickNode(Node.java:4891)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3900)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3486)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Scene.pick(Scene.java:1942)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Scene.access$6700(Scene.java:159)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3712)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
2019-08-26 22:25:58,222 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-08-26 22:25:58,223 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
2019-08-26 22:25:58,223 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
2019-08-26 22:25:58,223 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
2019-08-26 22:25:58,223 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-08-26 22:25:58,223 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
2019-08-26 22:25:58,223 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$248/2106142523.get(Unknown Source)
2019-08-26 22:25:58,223 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
2019-08-26 22:25:58,223 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
2019-08-26 22:25:58,223 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-08-26 22:25:58,223 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:927)
2019-08-26 22:25:58,225 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2019-08-26 22:25:58,225 ERROR - 	at java.util.ArrayList.elementData(ArrayList.java:418)
2019-08-26 22:25:58,225 ERROR - 	at java.util.ArrayList.get(ArrayList.java:431)
2019-08-26 22:25:58,225 ERROR - 	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
2019-08-26 22:25:58,225 ERROR - 	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
2019-08-26 22:25:58,225 ERROR - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1580)
2019-08-26 22:25:58,225 ERROR - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
2019-08-26 22:25:58,225 ERROR - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1377)
2019-08-26 22:25:58,225 ERROR - 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
2019-08-26 22:25:58,225 ERROR - 	at javafx.scene.Node.updateGeomBounds(Node.java:3556)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Node.getGeomBounds(Node.java:3509)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Node.getLocalBounds(Node.java:3457)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Node.impl_intersectsBounds(Node.java:4992)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2931)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Node.impl_pickNode(Node.java:4891)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3900)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3486)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Scene.pick(Scene.java:1942)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Scene.access$6700(Scene.java:159)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3712)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2019-08-26 22:25:58,226 ERROR - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
2019-08-26 22:25:58,226 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
2019-08-26 22:25:58,226 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
2019-08-26 22:25:58,226 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-08-26 22:25:58,226 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
2019-08-26 22:25:58,226 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$248/2106142523.get(Unknown Source)
2019-08-26 22:25:58,226 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
2019-08-26 22:25:58,226 ERROR - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
2019-08-26 22:25:58,226 ERROR - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2019-08-26 22:25:58,227 ERROR - 	at com.sun.glass.ui.View.notifyMouse(View.java:927)
2019-08-26 22:25:58,242 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2019-08-26 22:25:58,242 ERROR - 	at java.util.ArrayList.elementData(ArrayList.java:418)
2019-08-26 22:25:58,242 ERROR - 	at java.util.ArrayList.get(ArrayList.java:431)
2019-08-26 22:25:58,242 ERROR - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1580)
2019-08-26 22:25:58,242 ERROR - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
2019-08-26 22:25:58,242 ERROR - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1377)
2019-08-26 22:25:58,242 ERROR - 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Node.updateGeomBounds(Node.java:3556)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Node.getGeomBounds(Node.java:3509)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Node.getLocalBounds(Node.java:3457)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Node.updateTxBounds(Node.java:3620)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Node.getTransformedBounds(Node.java:3403)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Node.updateBounds(Node.java:538)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Parent.updateBounds(Parent.java:1708)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Parent.updateBounds(Parent.java:1706)
2019-08-26 22:25:58,243 ERROR - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2019-08-26 22:25:58,243 ERROR - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
2019-08-26 22:25:58,243 ERROR - 	at com.sun.javafx.tk.Toolkit$$Lambda$230/155431773.run(Unknown Source)
2019-08-26 22:25:58,243 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-08-26 22:25:58,243 ERROR - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
2019-08-26 22:25:58,243 ERROR - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
2019-08-26 22:25:58,243 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
2019-08-26 22:25:58,243 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
2019-08-26 22:25:58,244 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
2019-08-26 22:25:58,244 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$44/894170095.run(Unknown Source)
2019-08-26 22:25:58,244 ERROR - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2019-08-26 22:25:58,244 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2019-08-26 22:25:58,245 DEBUG - Playing graphic animation ...
2019-08-26 22:25:58,245 DEBUG - Playing sound animation ...
2019-08-26 22:25:58,245 DEBUG - Try to play data/common/sounds/applause.mp3
2019-08-26 22:25:58,245 DEBUG - using url
2019-08-26 22:25:58,245 DEBUG - path file:/Users/schwab/Documents/GazePlay2/gazeplay-data/target/classes/data/common/sounds/applause.mp3
2019-08-26 22:25:58,251 DEBUG - Finished JavaFX task
2019-08-26 22:25:58,272 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2019-08-26 22:25:58,272 ERROR - 	at java.util.ArrayList.elementData(ArrayList.java:418)
2019-08-26 22:25:58,272 ERROR - 	at java.util.ArrayList.get(ArrayList.java:431)
2019-08-26 22:25:58,272 ERROR - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1580)
2019-08-26 22:25:58,272 ERROR - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
2019-08-26 22:25:58,272 ERROR - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1377)
2019-08-26 22:25:58,272 ERROR - 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Node.updateGeomBounds(Node.java:3556)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Node.getGeomBounds(Node.java:3509)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Node.getLocalBounds(Node.java:3457)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Node.updateTxBounds(Node.java:3620)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Node.getTransformedBounds(Node.java:3403)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Node.updateBounds(Node.java:538)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Parent.updateBounds(Parent.java:1708)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Parent.updateBounds(Parent.java:1706)
2019-08-26 22:25:58,273 ERROR - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.javafx.tk.Toolkit$$Lambda$230/155431773.run(Unknown Source)
2019-08-26 22:25:58,273 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$44/894170095.run(Unknown Source)
2019-08-26 22:25:58,273 ERROR - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2019-08-26 22:25:58,281 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2019-08-26 22:25:58,281 ERROR - 	at java.util.ArrayList.elementData(ArrayList.java:418)
2019-08-26 22:25:58,281 ERROR - 	at java.util.ArrayList.get(ArrayList.java:431)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1580)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1377)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Node.updateGeomBounds(Node.java:3556)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Node.getGeomBounds(Node.java:3509)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Node.getLocalBounds(Node.java:3457)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Node.updateTxBounds(Node.java:3620)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Node.getTransformedBounds(Node.java:3403)
2019-08-26 22:25:58,281 ERROR - 	at javafx.scene.Node.updateBounds(Node.java:538)
2019-08-26 22:25:58,282 ERROR - 	at javafx.scene.Parent.updateBounds(Parent.java:1708)
2019-08-26 22:25:58,282 ERROR - 	at javafx.scene.Parent.updateBounds(Parent.java:1706)
2019-08-26 22:25:58,282 ERROR - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.javafx.tk.Toolkit$$Lambda$230/155431773.run(Unknown Source)
2019-08-26 22:25:58,282 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$44/894170095.run(Unknown Source)
2019-08-26 22:25:58,282 ERROR - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2019-08-26 22:25:58,286 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2019-08-26 22:25:58,296 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2019-08-26 22:25:58,296 ERROR - 	at java.util.ArrayList.elementData(ArrayList.java:418)
2019-08-26 22:25:58,296 ERROR - 	at java.util.ArrayList.get(ArrayList.java:431)
2019-08-26 22:25:58,296 ERROR - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1580)
2019-08-26 22:25:58,296 ERROR - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
2019-08-26 22:25:58,296 ERROR - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1377)
2019-08-26 22:25:58,296 ERROR - 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
2019-08-26 22:25:58,296 ERROR - 	at javafx.scene.Node.updateGeomBounds(Node.java:3556)
2019-08-26 22:25:58,296 ERROR - 	at javafx.scene.Node.getGeomBounds(Node.java:3509)
2019-08-26 22:25:58,296 ERROR - 	at javafx.scene.Node.getLocalBounds(Node.java:3457)
2019-08-26 22:25:58,296 ERROR - 	at javafx.scene.Node.updateTxBounds(Node.java:3620)
2019-08-26 22:25:58,297 ERROR - 	at javafx.scene.Node.getTransformedBounds(Node.java:3403)
2019-08-26 22:25:58,297 ERROR - 	at javafx.scene.Node.updateBounds(Node.java:538)
2019-08-26 22:25:58,297 ERROR - 	at javafx.scene.Parent.updateBounds(Parent.java:1708)
2019-08-26 22:25:58,297 ERROR - 	at javafx.scene.Parent.updateBounds(Parent.java:1706)
2019-08-26 22:25:58,297 ERROR - 	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.javafx.tk.Toolkit$$Lambda$230/155431773.run(Unknown Source)
2019-08-26 22:25:58,297 ERROR - 	at java.security.AccessController.doPrivileged(Native Method)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$44/894170095.run(Unknown Source)
2019-08-26 22:25:58,297 ERROR - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
2019-08-26 22:25:58,305 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2019-08-26 22:25:58,306 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException
2019-08-26 22:25:58,312 ERROR - Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
2019-08-26 22:25:58,312 ERROR - 	at java.util.ArrayList.elementData(ArrayList.java:418)
2019-08-26 22:25:58,312 ERROR - 	at java.util.ArrayList.get(ArrayList.java:431)
2019-08-26 22:25:58,312 ERROR - 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1580)
2019-08-26 22:25:58,312 ERROR - 	at javafx.scene.Parent.recomputeBounds(Parent.java:1524)
2019-08-26 22:25:58,312 ERROR - 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1377)
2019-08-26 22:25:58,312 ERROR - 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)
2019-08-26 22:25:58,312 ERROR - 	at javafx.scene.Node.updateGeomBounds(Node.java:3556)

**Comment by kuhlkrein** [comment]
Idk why but we were using a service in order to remove all the blocs before clearing the gamecontext... what led the system to try to access blocks after removing them, causing this error. we just need to remove this service and to clear the blocs before launching the new game. I'm on it. Will merge new PR soon
