### ISSUE TITLE
Tobii 4C doesn't work

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#94]
@coylz do you think we need to rebuild all dlls or to replace tobii dll will be enough ? Unfortunately, we don't have a windows with AMD here, I guess.

**Comment by schwabdidier** [comment]
It is something else, the proc seems to be a celeron

**Comment by schwabdidier** [comment]
[gazeplay.log](https://github.com/schwabdidier/GazePlay/files/1517328/gazeplay.log)

**Comment by schwabdidier** [comment]
The only difference with what I have is Windows 10 instead of Windows 7.

**Comment by schwabdidier** [comment]
The problem appears to be different with new version of GazePlay (1.1.0). 

I just took the control of the computer. nothing was working with current configuration (it may be a bug). I changed to "mouse control", then home then came back to config to change back to tobii and then black screen. Restart game, black screen. 

`2017-12-26 13:59:25,084 [main]                         DEBUG uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4JInitialiser - Your logging framework class ch.qos.logback.classic.Logger should not need access to the standard println methods on the console, so you should not need to register a logging system package.
2017-12-26 13:59:25,148 [main]                         INFO  uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
2017-12-26 13:59:25,169 [main]                         INFO  uk.org.lidalia.sysoutslf4j.context.SysOutOverSLF4J - Redirected System.out and System.err to SLF4J for this context
2017-12-26 13:59:25,177 [main]                         INFO  net.gazeplay.GazePlayLauncher - ***********************
2017-12-26 13:59:25,178 [main]                         INFO  net.gazeplay.GazePlayLauncher - ***********************
2017-12-26 13:59:25,186 [main]                         INFO  net.gazeplay.GazePlayLauncher - ***********************
2017-12-26 13:59:25,187 [main]                         INFO  net.gazeplay.GazePlayLauncher - ***********************
2017-12-26 13:59:25,187 [main]                         INFO  net.gazeplay.GazePlayLauncher - ***********************
2017-12-26 13:59:25,188 [main]                         INFO  net.gazeplay.GazePlayLauncher - GazePlay
2017-12-26 13:59:25,188 [main]                         INFO  net.gazeplay.GazePlayLauncher - Version : 1.1.0-SNAPSHOT (2017-12-17T17:24:32Z)
2017-12-26 13:59:25,198 [main]                         INFO  utils.games.Utils - java.runtime.name: Java(TM) SE Runtime Environment
2017-12-26 13:59:25,202 [main]                         INFO  utils.games.Utils - sun.boot.library.path: C:\Program Files\Java\jre1.8.0_151\bin
2017-12-26 13:59:25,203 [main]                         INFO  utils.games.Utils - java.vm.version: 25.151-b12
2017-12-26 13:59:25,204 [main]                         INFO  utils.games.Utils - java.vm.vendor: Oracle Corporation
2017-12-26 13:59:25,205 [main]                         INFO  utils.games.Utils - java.vendor.url: http://java.oracle.com/
2017-12-26 13:59:25,205 [main]                         INFO  utils.games.Utils - path.separator: ;
2017-12-26 13:59:25,205 [main]                         INFO  utils.games.Utils - java.vm.name: Java HotSpot(TM) 64-Bit Server VM
2017-12-26 13:59:25,205 [main]                         INFO  utils.games.Utils - file.encoding.pkg: sun.io
2017-12-26 13:59:25,207 [main]                         INFO  utils.games.Utils - user.script: 
2017-12-26 13:59:25,208 [main]                         INFO  utils.games.Utils - user.country: FR
2017-12-26 13:59:25,209 [main]                         INFO  utils.games.Utils - sun.java.launcher: SUN_STANDARD
2017-12-26 13:59:25,210 [main]                         INFO  utils.games.Utils - sun.os.patch.level: 
2017-12-26 13:59:25,211 [main]                         INFO  utils.games.Utils - java.vm.specification.name: Java Virtual Machine Specification
2017-12-26 13:59:25,228 [main]                         INFO  utils.games.Utils - user.dir: C:\Users\katel\GazePlay\bin
2017-12-26 13:59:25,229 [main]                         INFO  utils.games.Utils - java.runtime.version: 1.8.0_151-b12
2017-12-26 13:59:25,230 [main]                         INFO  utils.games.Utils - java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
2017-12-26 13:59:25,230 [main]                         INFO  utils.games.Utils - java.endorsed.dirs: C:\Program Files\Java\jre1.8.0_151\lib\endorsed
2017-12-26 13:59:25,230 [main]                         INFO  utils.games.Utils - os.arch: amd64
2017-12-26 13:59:25,230 [main]                         INFO  utils.games.Utils - java.io.tmpdir: C:\Users\katel\AppData\Local\Temp\
2017-12-26 13:59:25,230 [main]                         INFO  utils.games.Utils - line.separator: 

2017-12-26 13:59:25,230 [main]                         INFO  utils.games.Utils - java.vm.specification.vendor: Oracle Corporation
2017-12-26 13:59:25,231 [main]                         INFO  utils.games.Utils - user.variant: 
2017-12-26 13:59:25,231 [main]                         INFO  utils.games.Utils - os.name: Windows 10
2017-12-26 13:59:25,231 [main]                         INFO  utils.games.Utils - sun.jnu.encoding: Cp1252
2017-12-26 13:59:25,232 [main]                         INFO  utils.games.Utils - java.library.path: C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\TXE Components\iCLS\;C:\Program Files\Intel\TXE Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Intel\TXE Components\DAL\;C:\Program Files (x86)\Intel\TXE Components\DAL\;C:\Program Files\Intel\TXE Components\IPT\;C:\Program Files (x86)\Intel\TXE Components\IPT\;C:\Users\katel\AppData\Local\Microsoft\WindowsApps;;.
2017-12-26 13:59:25,232 [main]                         INFO  utils.games.Utils - java.specification.name: Java Platform API Specification
2017-12-26 13:59:25,232 [main]                         INFO  utils.games.Utils - java.class.version: 52.0
2017-12-26 13:59:25,232 [main]                         INFO  utils.games.Utils - sun.management.compiler: HotSpot 64-Bit Tiered Compilers
2017-12-26 13:59:25,232 [main]                         INFO  utils.games.Utils - os.version: 10.0
2017-12-26 13:59:25,232 [main]                         INFO  utils.games.Utils - user.home: C:\Users\katel
2017-12-26 13:59:25,233 [main]                         INFO  utils.games.Utils - user.timezone: Europe/Paris
2017-12-26 13:59:25,233 [main]                         INFO  utils.games.Utils - java.awt.printerjob: sun.awt.windows.WPrinterJob
2017-12-26 13:59:25,233 [main]                         INFO  utils.games.Utils - file.encoding: Cp1252
2017-12-26 13:59:25,233 [main]                         INFO  utils.games.Utils - java.specification.version: 1.8
2017-12-26 13:59:25,233 [main]                         INFO  utils.games.Utils - user.name: katel
2017-12-26 13:59:25,234 [main]                         INFO  utils.games.Utils - java.class.path: ..\lib\gazeplay-1.1.0-SNAPSHOT.jar
2017-12-26 13:59:25,234 [main]                         INFO  utils.games.Utils - java.vm.specification.version: 1.8
2017-12-26 13:59:25,235 [main]                         INFO  utils.games.Utils - sun.arch.data.model: 64
2017-12-26 13:59:25,235 [main]                         INFO  utils.games.Utils - java.home: C:\Program Files\Java\jre1.8.0_151
2017-12-26 13:59:25,235 [main]                         INFO  utils.games.Utils - sun.java.command: ..\lib\gazeplay-1.1.0-SNAPSHOT.jar
2017-12-26 13:59:25,235 [main]                         INFO  utils.games.Utils - java.specification.vendor: Oracle Corporation
2017-12-26 13:59:25,235 [main]                         INFO  utils.games.Utils - user.language: fr
2017-12-26 13:59:25,235 [main]                         INFO  utils.games.Utils - awt.toolkit: sun.awt.windows.WToolkit
2017-12-26 13:59:25,235 [main]                         INFO  utils.games.Utils - java.vm.info: mixed mode
2017-12-26 13:59:25,235 [main]                         INFO  utils.games.Utils - java.version: 1.8.0_151
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - java.ext.dirs: C:\Program Files\Java\jre1.8.0_151\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - sun.boot.class.path: C:\Program Files\Java\jre1.8.0_151\lib\resources.jar;C:\Program Files\Java\jre1.8.0_151\lib\rt.jar;C:\Program Files\Java\jre1.8.0_151\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_151\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_151\lib\jce.jar;C:\Program Files\Java\jre1.8.0_151\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_151\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_151\classes
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - sun.stderr.encoding: cp850
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - java.vendor: Oracle Corporation
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - file.separator: \
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - java.vendor.url.bug: http://bugreport.sun.com/bugreport/
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - sun.cpu.endian: little
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - sun.io.unicode.encoding: UnicodeLittle
2017-12-26 13:59:25,236 [main]                         INFO  utils.games.Utils - sun.stdout.encoding: cp850
2017-12-26 13:59:25,241 [main]                         INFO  utils.games.Utils - sun.desktop: windows
2017-12-26 13:59:25,252 [main]                         INFO  utils.games.Utils - sun.cpu.isalist: amd64
2017-12-26 13:59:25,253 [main]                         INFO  net.gazeplay.GazePlayLauncher - Max Memory: 954728448
2017-12-26 13:59:27,136 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - Screen size: 1600 X 900
2017-12-26 13:59:27,141 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - ***********************
2017-12-26 13:59:27,141 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - ***********************
2017-12-26 13:59:27,141 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - ***********************
2017-12-26 13:59:27,141 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - ***********************
2017-12-26 13:59:27,141 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - ***********************
2017-12-26 13:59:27,146 [JavaFX Application Thread]    INFO  gaze.configuration.Configuration - Properties loaded : {FILEDIR=C:\Users\katel\GazePlay\files\, WHEREISITDIR=, EYETRACKER=tobii_eyeX_4C, LANGUAGE=fra, FIXATIONLENGTH=500, CSSFILE=data/stylesheets/main-green.css}
2017-12-26 13:59:27,149 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - [data/stylesheets/main-green.css]
2017-12-26 13:59:27,198 [JavaFX Application Thread]    INFO  gaze.configuration.Configuration - Properties loaded : {FILEDIR=C:\Users\katel\GazePlay\files\, WHEREISITDIR=, EYETRACKER=tobii_eyeX_4C, LANGUAGE=fra, FIXATIONLENGTH=500, CSSFILE=data/stylesheets/main-green.css}
2017-12-26 13:59:27,282 [JavaFX Application Thread]    INFO  net.gazeplay.DefaultGamesLocator - Games found : 24
2017-12-26 13:59:36,087 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - Game number: 0
2017-12-26 13:59:36,087 [JavaFX Application Thread]    INFO  net.gazeplay.GazePlay - Tartes à la crème
2017-12-26 13:59:36,088 [JavaFX Application Thread]    INFO  net.gazeplay.utils.stats.Stats - computeHeatMapPixelSize() : result = 8.0
2017-12-26 13:59:37,348 [pool-2-thread-1]              INFO  com.theeyetribe.clientsdk.GazeApiManager - Socket connection not available: Connection refused: connect
2017-12-26 13:59:37,353 [JavaFX Application Thread]    INFO  gaze.configuration.Configuration - Properties loaded : {FILEDIR=C:\Users\katel\GazePlay\files\, WHEREISITDIR=, EYETRACKER=tobii_eyeX_4C, LANGUAGE=fra, FIXATIONLENGTH=500, CSSFILE=data/stylesheets/main-green.css}
2017-12-26 13:59:37,353 [JavaFX Application Thread]    INFO  gaze.GazeUtils - Eye-tracker = tobii_eyeX_4C
2017-12-26 13:59:37,367 [JavaFX Application Thread]    INFO  tobii.Tobii - ******************************************************
2017-12-26 13:59:37,367 [JavaFX Application Thread]    INFO  tobii.Tobii - If you wish to Use a Tobii 4C or a Tobii EyeX
2017-12-26 13:59:37,367 [JavaFX Application Thread]    INFO  tobii.Tobii - Please put appropriate DLLs in DLL folder :
2017-12-26 13:59:37,367 [JavaFX Application Thread]    INFO  tobii.Tobii - tobii_stream_engine.dll and GazePlayTobiiLibrary2.dll
2017-12-26 13:59:37,367 [JavaFX Application Thread]    INFO  tobii.Tobii - should be in
2017-12-26 13:59:37,367 [JavaFX Application Thread]    INFO  tobii.Tobii - C:\Users\katel\GazePlay\DLL\
2017-12-26 13:59:37,367 [JavaFX Application Thread]    INFO  tobii.Tobii - ******************************************************
2017-12-26 13:59:37,369 [JavaFX Application Thread]    ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: tobii.Tobii.init()I
2017-12-26 13:59:37,369 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at tobii.Tobii.init(Native Method)
2017-12-26 13:59:37,369 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at tobii.Tobii.execProg(Tobii.java:43)
2017-12-26 13:59:37,369 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at gaze.GazeUtils.createGazeListener(GazeUtils.java:40)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at gaze.GazeUtils.<clinit>(GazeUtils.java:26)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.utils.stats.Stats.<init>(Stats.java:67)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.utils.stats.ShootGamesStats.<init>(ShootGamesStats.java:14)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.games.creampie.CreampieStats.<init>(CreampieStats.java:9)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.DefaultGamesLocator.lambda$listGames$11(DefaultGamesLocator.java:35)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GameSpec.launch(GameSpec.java:30)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GazePlay.chooseGame(GazePlay.java:117)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GazePlay.access$000(GazePlay.java:25)
2017-12-26 13:59:37,370 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GazePlay$1.changed(GazePlay.java:97)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at net.gazeplay.GazePlay$1.changed(GazePlay.java:93)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:72)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:68)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.control.SingleSelectionModel.updateSelectedIndex(SingleSelectionModel.java:215)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.control.SingleSelectionModel.select(SingleSelectionModel.java:149)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.control.ChoiceBox$ChoiceBoxSelectionModel.select(ChoiceBox.java:573)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.scene.control.skin.ChoiceBoxSkin.lambda$addPopupItem$284(ChoiceBoxSkin.java:261)
2017-12-26 13:59:37,372 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.event.Event.fireEvent(Event.java:198)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2017-12-26 13:59:37,373 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.event.Event.fireEvent(Event.java:198)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
2017-12-26 13:59:37,374 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.security.AccessController.doPrivileged(Native Method)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:417)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.View.notifyMouse(View.java:937)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
2017-12-26 13:59:37,375 [JavaFX Application Thread]    ERROR java.lang.Throwable - 	at java.lang.Thread.run(Unknown Source)`

**Comment by schwabdidier** [comment]
I reinstalled everything and there is still this exception. We will see that when we met at lab @coylz, I guess all updates (especially new dll + integration in jar) will resolve that problem.

**Comment by schwabdidier** [comment]
We have that with different people... They can't use GazePlay with Tobii 4C. I found that Tobii upgraded their drivers but even with older drivers, we weren't able to use GazePlay. Drivers were exactly the same as the ones on my computer (but my computer is a windows seven while the other is a windows 10).

Old driver came from https://www.touslesdrivers.com/index.php?v_page=26&v_code=1703

**Comment by schwabdidier** [comment]
Managed throw [TobiiStreamEngineForJava project](https://github.com/coylz/TobiiStreamEngineForJava)
